part of 'catch_field.dart';

typedef _RowConfig = ({
  int titleMaxLines,
  int bodyMaxLines,
  bool contentRow,
  String? inlineMetadata,
  String? valueText,
  int valueMaxLines,
  bool? showChevron,
  String? placeholder,
  CatchFieldLabelTextMode labelMode,
  String? error,
  String? errorText,
  bool valid,
  VoidCallback? onTap,
  bool add,
  bool navigation,
});

typedef _ToggleConfig = ({
  bool value,
  ValueChanged<bool>? onToggleChanged,
  String? contractExemption,
  int titleMaxLines,
  int bodyMaxLines,
  String? helperText,
  String? badgeLabel,
  CatchBadgeTone? badgeTone,
});

typedef _EditConfig = ({
  TextEditingController? controller,
  String? contractExemption,
  String? initialValue,
  ValueChanged<String>? onChanged,
  ValueChanged<String>? onSubmitted,
  ValueChanged<String>? onBlur,
  ValueChanged<bool>? onFocusChanged,
  FocusNode? focusNode,
  VoidCallback? onEditingComplete,
  FormFieldValidator<String>? onValidate,
  TextInputType? keyboardType,
  TextInputAction? textInputAction,
  TextCapitalization textCapitalization,
  List<TextInputFormatter>? inputFormatters,
  Iterable<String>? autofillHints,
  CatchTextInputVariant inputVariant,
  int? maxLines,
  int? minLines,
  int? maxLength,
  CatchTextInputMode inputMode,
  bool autofocus,
  CatchFieldSize size,
  TextAlign textAlign,
  List<FontFeature>? fontFeatures,
  String? prefixText,
  String? suffixText,
  bool showClearButton,
  String? placeholder,
  String? emptyValueText,
  String? inputHint,
  String? leadingUnit,
  String? error,
  String? errorText,
  VoidCallback? onTap,
  CatchFieldLabelTextMode labelMode,
  String? helperText,
  CatchFieldSupportRowTone helperTone,
  bool explicitSave,
  bool? open,
  ValueChanged<bool>? onOpenChanged,
  VoidCallback? onCancel,
  VoidCallback? onSubmit,
});

typedef _SelectConfig = ({
  List<Object?> values,
  String? contractExemption,
  String Function(Object? item) itemLabelBuilder,
  Object? value,
  ValueChanged<Object?>? onSelectChanged,
  FormFieldValidator<Object?>? selectValidator,
  String? placeholder,
  bool showLabel,
  CatchFieldSize size,
  String? helperText,
  CatchFieldSupportRowTone helperTone,
});

typedef _ControlConfig = ({
  String? contractExemption,
  int titleMaxLines,
  int bodyMaxLines,
  CatchFieldMode disclosureMode,
  ValueChanged<bool>? onOpenChanged,
  VoidCallback? onCancel,
  VoidCallback? onSubmit,
  bool addable,
  CatchFieldLabelTextMode labelMode,
  String? helperText,
  String? placeholder,
  String? emptyValueText,
  String? error,
  String? errorText,
});
