part of 'catch_field.dart';

typedef _RowConfig = ({
  int titleMaxLines,
  int bodyMaxLines,
  bool contentRow,
  String? inlineMetadata,
  String? valueText,
  int valueMaxLines,
  bool? showChevron,
  String? placeholder,
  bool isOptional,
  String? error,
  String? errorText,
  bool valid,
  VoidCallback? onTap,
  bool add,
  bool navigation,
});

typedef _ToggleConfig = ({
  bool value,
  ValueChanged<bool>? onToggleChanged,
  String? contractExemption,
  int titleMaxLines,
  int bodyMaxLines,
  String? helperText,
  String? badgeLabel,
  CatchBadgeTone? badgeTone,
});

typedef _EditConfig = ({
  TextEditingController? controller,
  String? contractExemption,
  String? initialValue,
  ValueChanged<String>? onChanged,
  ValueChanged<String>? onSubmitted,
  ValueChanged<String>? onBlur,
  ValueChanged<bool>? onFocusChanged,
  FocusNode? focusNode,
  bool retainFocusOnSubmitted,
  FormFieldValidator<String>? validator,
  TextInputType? keyboardType,
  TextInputAction? textInputAction,
  TextCapitalization textCapitalization,
  List<TextInputFormatter>? inputFormatters,
  Iterable<String>? autofillHints,
  bool obscureText,
  int? maxLines,
  int? minLines,
  int? maxLength,
  bool readOnly,
  bool autofocus,
  bool showLabel,
  CatchFieldSize size,
  TextAlign textAlign,
  bool mono,
  String? prefixText,
  String? suffixText,
  bool showClearButton,
  bool floatingLabel,
  String? placeholder,
  String? emptyValueText,
  String? inputHint,
  String? leadingUnit,
  String? error,
  String? errorText,
  VoidCallback? onTap,
  bool isOptional,
  String? helperText,
  CatchFieldSupportRowTone helperTone,
  bool focused,
  bool explicitSave,
  bool? open,
  ValueChanged<bool>? onOpenChanged,
  VoidCallback? onCancel,
  VoidCallback? onSubmit,
  bool isLoading,
});

typedef _SelectConfig = ({
  List<Object?> values,
  String? contractExemption,
  String Function(Object? item) itemLabel,
  Object? value,
  ValueChanged<Object?>? onSelectChanged,
  FormFieldValidator<Object?>? selectValidator,
  String? placeholder,
  bool showLabel,
  CatchFieldSize size,
  String? helperText,
  CatchFieldSupportRowTone helperTone,
});

typedef _ControlConfig = ({
  String? contractExemption,
  int titleMaxLines,
  int bodyMaxLines,
  bool? open,
  bool initiallyOpen,
  ValueChanged<bool>? onOpenChanged,
  VoidCallback? onCancel,
  VoidCallback? onSubmit,
  bool isLoading,
  bool addable,
  bool isOptional,
  String? helperText,
  String? placeholder,
  String? emptyValueText,
  String? error,
  String? errorText,
});
