include: package:flutter_lints/flutter.yaml

plugins:
  riverpod_lint: 3.1.3

analyzer:
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    # Style
    - prefer_single_quotes
    - directives_ordering
    - sort_child_properties_last
    - use_super_parameters

    # Safety
    - avoid_dynamic_calls
    - cancel_subscriptions
    - close_sinks
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - throw_in_finally
    - unawaited_futures

    # Correctness
    - always_use_package_imports
