import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('Consumer iOS launch mark uses generated responsive reel geometry', () {
    final consumerLaunch = File(
      'apps/consumer/ios/Runner/Base.lproj/LaunchScreen.storyboard',
    ).readAsStringSync();
    final hostLaunch = File(
      'ios/Runner/Base.lproj/LaunchScreen.storyboard',
    ).readAsStringSync();

    expect(
      consumerLaunch,
      contains('Generated by tool/branding/generate_native_brand_assets.dart.'),
    );
    expect(
      consumerLaunch,
      contains(
        'firstAttribute="leading" relation="greaterThanOrEqual" '
        'secondItem="Ze5-6b-2t3" secondAttribute="leading" constant="1"',
      ),
    );
    expect(
      consumerLaunch,
      contains(
        'firstAttribute="centerX" secondItem="Ze5-6b-2t3" '
        'secondAttribute="centerX" constant="-145" priority="750"',
      ),
    );
    expect(
      consumerLaunch,
      contains(
        'firstAttribute="top" relation="greaterThanOrEqual" '
        'secondItem="Ze5-6b-2t3" secondAttribute="top" constant="198"',
      ),
    );
    expect(
      consumerLaunch,
      contains(
        'firstAttribute="top" relation="greaterThanOrEqual" '
        'secondItem="6Tk-OE-BBY" secondAttribute="top" constant="152"',
      ),
    );
    expect(consumerLaunch, contains('firstAttribute="width" constant="138"'));
    expect(consumerLaunch, contains('firstAttribute="height" constant="138"'));
    expect(hostLaunch, isNot(contains('generate_native_brand_assets.dart')));
  });
}
