import type {MarketPack} from "./types";

export const inMarket = {
  id: "in",
  countryCode: "IN",
  appStoreCountryCodes: ["IN"],
  locale: "en-IN",
  currencyCode: "INR",
  currencySymbol: "₹",
  cities: [
    {
      id: "in-mumbai",
      slug: "mumbai",
      label: "Mumbai",
      aliases: [],
      timezone: "Asia/Kolkata",
      status: "live",
    },
    {
      id: "in-indore",
      slug: "indore",
      label: "Indore",
      aliases: [],
      timezone: "Asia/Kolkata",
      status: "live",
    },
    {
      id: "in-delhi",
      slug: "delhi",
      label: "Delhi",
      aliases: ["Delhi NCR", "New Delhi"],
      timezone: "Asia/Kolkata",
      status: "waitlist",
    },
    {
      id: "in-bangalore",
      slug: "bangalore",
      label: "Bangalore",
      aliases: ["Bengaluru"],
      timezone: "Asia/Kolkata",
      status: "waitlist",
    },
    {
      id: "in-pune",
      slug: "pune",
      label: "Pune",
      aliases: [],
      timezone: "Asia/Kolkata",
      status: "waitlist",
    },
    {
      id: "in-hyderabad",
      slug: "hyderabad",
      label: "Hyderabad",
      aliases: [],
      timezone: "Asia/Kolkata",
      status: "waitlist",
    },
  ],
  featuredCityId: "in-mumbai",
  otherCityOptionLabel: "Other",
  heroEyebrowTemplate: "LIVE IN {cities}",
  heroTicketLabelTemplate: "THIS WEEK IN {city}",
  downloadBodyTemplate:
    "Download the app to see this week's events in {cities}. More cities soon.",
  comparisonColumns: [
    "Catch",
    "Luma",
    "Eventbrite",
    "District",
    "BookMyShow",
    "Instagram + WhatsApp",
    "Forms + sheets",
  ],
  exampleEvent: {
    name: "Sunday Table Club",
    venue: "Pali Village Cafe",
    cityId: "in-mumbai",
    timezone: "Asia/Kolkata",
    currencyCode: "INR",
  },
} satisfies MarketPack;
