#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {fromRepo} from "../lib/repo_paths.mjs";
import {collectProductionWidgetClassificationDeclarations} from "./generate_widget_classification.mjs";
import {componentLevels as levels, roleNouns, sharedWidgetLevel} from "./component_naming.mjs";

export const catalogStart = "<!-- BEGIN GENERATED WIDGET INVENTORY -->";
export const catalogEnd = "<!-- END GENERATED WIDGET INVENTORY -->";
const catalogPath = "docs/widget_catalog.md";

/** Preserve every public production Widget; registry metadata never filters it. */
export function buildCatalogRows({declarations, components}) {
  const identities = new Map();
  for (const component of components) {
    addIdentity(component.dart?.symbol, component.dart?.file, component);
    for (const member of component.contract?.members ?? []) {
      addIdentity(member.symbol, member.file ?? component.dart?.file, member);
    }
  }

  const seen = new Set();
  const rows = declarations
    .filter((entry) => entry.classKind === "widget" && entry.visibility === "public")
    .map((entry) => {
      const identity = `${entry.file}:${entry.name}`;
      if (seen.has(identity)) throw new Error(`Duplicate source declaration: ${identity}`);
      seen.add(identity);
      const record = identities.get(entry.name);
      if (record && record.file !== entry.file) {
        throw new Error(`${entry.name}: registry path ${record.file} differs from source ${entry.file}`);
      }
      const homeLevel = sharedWidgetLevel(entry.file);
      if (homeLevel && !record) {
        throw new Error(`${identity}: shared Widget has no component-registry identity`);
      }
      if (record && (!levels.includes(record.level) || !roleNouns.includes(record.roleNoun))) {
        throw new Error(`${identity}: registry level and roleNoun are required`);
      }
      if (homeLevel && record.level !== homeLevel) {
        throw new Error(`${identity}: registry level ${record.level} disagrees with source home ${homeLevel}`);
      }
      // Feature levels use the existing route/screen naming boundary. Registered
      // metadata remains authoritative for reviewed domain and adapter surfaces.
      const level = record?.level ?? (
        /(?:Screen|Page|Route|App)$/u.test(entry.name) ? "L6" : "L5"
      );
      const documentation = classPurpose(entry.source, entry.line);
      return {
        name: entry.name,
        file: entry.file,
        line: entry.line,
        level,
        roleNoun: record?.roleNoun ?? null,
        conceptId: record?.governance?.conceptId ?? null,
        purpose: documentation || record?.summary || null,
        purposeSource: documentation ? "class-doc" : record?.summary ? "registry" : "missing",
      };
    });
  return rows.sort((a, b) =>
    compare(a.level, b.level) || compare(a.file, b.file) || compare(a.name, b.name));

  function addIdentity(symbol, file, record) {
    if (!symbol || !file) throw new Error(`${record.id}: registry symbol and file are required`);
    if (identities.has(symbol)) throw new Error(`Duplicate registry identity: ${symbol}`);
    identities.set(symbol, {...record, file});
  }
}

/** Read only documentation attached to this declaration, never a nearby field. */
export function classPurpose(source, line) {
  const before = source.split(/\r?\n/u).slice(0, line - 1).join("\n");
  const annotations = String.raw`(?:\s*@[A-Za-z_$][\w.$]*(?:\([^;{}]*\))?)*\s*(?![\s\S])`;
  const lineDoc = before.match(new RegExp(
    String.raw`((?:^[ \t]*\/\/\/[^\n]*(?:\n|$))+)${annotations}`, "mu",
  ));
  if (lineDoc) {
    return firstParagraph(lineDoc[1].split("\n").map((value) =>
      value.replace(/^[ \t]*\/\/\/[ ]?/u, "")));
  }
  const blockDoc = before.match(new RegExp(
    String.raw`\/\*\*((?:(?!\*\/)[\s\S])*)\*\/${annotations}`, "u",
  ));
  return blockDoc ? firstParagraph(blockDoc[1].split("\n").map((value) =>
    value.replace(/^\s*\* ?/u, "").trim())) : "";
}

export function renderCatalogInventory(rows) {
  const missing = rows.filter((row) => row.purposeSource === "missing").length;
  const output = [
    catalogStart,
    "<!-- Generated by tool/design/generate_widget_catalog.mjs. Do not edit this region. -->",
    "## Production Widget Inventory",
    "",
    `${rows.length} public production Widgets. Source discovery determines membership; ` +
      "the component registry supplies reviewed identity and ladder metadata.",
    "",
    "Purpose comes from the first class documentation paragraph, then the registry summary. " +
      `${missing} declarations have neither and remain visible as undocumented. ` +
      "Unregistered feature Widgets use the existing screen-name boundary for L5/L6; " +
      "that source classification is not a semantic conformance verdict.",
  ];
  for (const level of levels) {
    const entries = rows.filter((row) => row.level === level);
    if (entries.length === 0) continue;
    output.push("", `### ${level} (${entries.length})`, "",
      "| Widget | Source | Role | Canonical concept | Purpose |",
      "|---|---|---|---|---|");
    for (const entry of entries) {
      output.push(`| ${code(entry.name)} | ${code(`${entry.file}:${entry.line}`)} | ` +
        `${entry.roleNoun ? code(entry.roleNoun) : "—"} | ` +
        `${entry.conceptId ? code(entry.conceptId) : "—"} | ` +
        `${cell(entry.purpose ?? "No class documentation or registry summary.")} |`);
    }
  }
  output.push("", catalogEnd);
  return output.join("\n");
}

export function replaceCatalogInventory(document, inventory) {
  if (document.split(catalogStart).length !== 2 || document.split(catalogEnd).length !== 2) {
    throw new Error("Catalog must contain exactly one generated inventory region");
  }
  const start = document.indexOf(catalogStart);
  const end = document.indexOf(catalogEnd);
  if (end < start) throw new Error("Catalog generated inventory markers are reversed");
  return document.slice(0, start) + inventory + document.slice(end + catalogEnd.length);
}

export function buildWidgetCatalog({repoRoot = fromRepo(".")} = {}) {
  const registry = JSON.parse(fs.readFileSync(
    path.join(repoRoot, "design/components/catch.components.json"), "utf8"));
  return buildCatalogRows({
    declarations: collectProductionWidgetClassificationDeclarations({repoRoot}),
    components: registry.components ?? [],
  });
}

export function runCatalog({repoRoot = fromRepo("."), mode = "check"} = {}) {
  if (!["check", "write", "json"].includes(mode)) throw new Error(`Unknown catalog mode: ${mode}`);
  const rows = buildWidgetCatalog({repoRoot});
  if (mode === "json") return {rows};
  const file = path.join(repoRoot, catalogPath);
  const before = fs.readFileSync(file, "utf8");
  const after = replaceCatalogInventory(before, renderCatalogInventory(rows));
  if (mode === "check" && before !== after) {
    throw new Error("Widget catalog is stale or hand-edited; run node tool/design/generate_widget_catalog.mjs --write");
  }
  if (mode === "write" && before !== after) fs.writeFileSync(file, after);
  return {count: rows.length, changed: before !== after};
}

function firstParagraph(lines) {
  const result = [];
  for (const line of lines) {
    if (!line.trim() && result.length) break;
    if (line.trim()) result.push(line.trim());
  }
  return result.join(" ");
}

function cell(value) {
  return String(value).replaceAll("&", "&amp;").replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;").replaceAll("|", "&#124;").replaceAll(/\s+/gu, " ").trim();
}
function code(value) { return `<code>${cell(value).replaceAll("`", "&#96;")}</code>`; }
function compare(a, b) { return a < b ? -1 : a > b ? 1 : 0; }

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  try {
    const args = process.argv.slice(2);
    if (args.includes("--help")) {
      console.log("Usage: node tool/design/generate_widget_catalog.mjs [--check|--write|--json] [--repo-root <path>]");
    } else {
      let mode = "check";
      let selectedMode = false;
      let repoRoot = fromRepo(".");
      for (let i = 0; i < args.length; i += 1) {
        if (args[i] === "--repo-root" && args[i + 1] && !args[i + 1].startsWith("--")) {
          repoRoot = path.resolve(args[++i]);
        } else if (["--check", "--write", "--json"].includes(args[i]) && !selectedMode) {
          mode = args[i].slice(2);
          selectedMode = true;
        } else throw new Error(`Unknown, missing or conflicting argument: ${args[i]}`);
      }
      const result = runCatalog({repoRoot, mode});
      console.log(mode === "json" ? JSON.stringify(result, null, 2) :
        `Widget catalog ${mode === "write" ? "generated" : "check passed"} (${result.count} public Widgets).`);
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
