/**
 * Firestore document interfaces for Cloud Functions.
 *
 * AUTO-GENERATED by tool/contracts/generate_firestore_types.dart
 * DO NOT EDIT DIRECTLY.
 *
 * To update: dart tool/contracts/generate_firestore_types.dart
 *
 * Transitional Admin SDK typing facade. JSON Schema contracts are the
 * canonical persisted-data source; this file only exists while Functions
 * code still needs live FirebaseFirestore.Timestamp-oriented types.
 *
 * These mirror the Dart freezed models in lib/<feature>/domain/<Model>.dart.
 * Enum values match what Dart's json_serializable serialises by default
 * (enum member name, camelCase — e.g. DrinkingHabit.socially → "socially").
 *
 * Fields marked with @JsonKey(includeToJson: false) in Dart are the
 * document ID and are NOT stored inside the document data.
 *
 * Timestamps are stored as Firestore timestamps in the DB. In admin SDK
 * code, use FirebaseFirestore.Timestamp and FieldValue.serverTimestamp()
 * to write.
 */

// FirebaseFirestore.Timestamp is available globally via
// @google-cloud/firestore, a transitive dependency of firebase-admin.

// ── Shared enum types ────────────────────────────────────────────────────

export type ActivityNotificationType =
  | "message"
  | "match"
  | "eventReminder"
  | "eventSignup"
  | "waitlistPromotion"
  | "eventCancelled"
  | "eventUpdated"
  | "clubUpdate";

export type ChildrenStatus =
  | "dontHave"
  | "haveWantMore"
  | "haveNoMore"
  | "wantSomeday"
  | "dontWant";

export type ClubHostRole = "owner" | "host";

export type ClubLifecycleStatus = "active" | "archived";

export type ClubMembershipRole = "owner" | "host" | "member";

export type ClubMembershipStatus = "active" | "left" | "deleted";

export type DietaryPreference =
  | "omnivore"
  | "vegetarian"
  | "vegan"
  | "jain"
  | "other";

export type DrinkingHabit = "never" | "socially" | "often";

export type EducationLevel =
  | "highSchool"
  | "someCollege"
  | "bachelors"
  | "masters"
  | "phd"
  | "tradeSchool"
  | "other";

export type EventAdmissionDefaultPreset =
  | "openCapacity"
  | "inviteOnly"
  | "balancedSingles"
  | "fixedCohortCaps";

export type EventCancellationPolicyId = "flexible" | "standard" | "strict";

export type EventLifecycleStatus = "active" | "cancelled";

export type EventParticipationStatus =
  | "signedUp"
  | "waitlisted"
  | "attended"
  | "cancelled"
  | "deleted";

export type Gender = "man" | "woman" | "nonBinary" | "other";

export type Language =
  | "english"
  | "hindi"
  | "marathi"
  | "tamil"
  | "telugu"
  | "kannada"
  | "bengali"
  | "gujarati"
  | "punjabi"
  | "malayalam"
  | "odia"
  | "other";

export type MatchStatus = "active" | "blocked";

export type PaceLevel = "easy" | "moderate" | "fast" | "competitive";

export type PaymentStatus = "pending" | "completed" | "failed" | "refunded";

export type PreferredDistance = "fiveK" | "tenK" | "halfMarathon" | "marathon";

export type PreferredRunTime =
  | "earlyMorning"
  | "morning"
  | "afternoon"
  | "evening"
  | "night";

export type RelationshipGoal =
  | "relationship"
  | "casual"
  | "marriage"
  | "friendship"
  | "unsure";

export type Religion =
  | "hindu"
  | "muslim"
  | "christian"
  | "sikh"
  | "jain"
  | "buddhist"
  | "other"
  | "nonReligious";

export type RunReason =
  | "fitness"
  | "community"
  | "mindfulness"
  | "challenge"
  | "weightLoss"
  | "raceTraining"
  | "social";

export type SmokingHabit = "never" | "occasionally" | "often";

export type SwipeDirection = "like" | "pass";

export type SwipeReactionTargetType =
  | "heroPhoto"
  | "photo"
  | "profilePrompt"
  | "compatibility"
  | "running"
  | "details"
  | "lifestyle";

export type WorkoutFrequency = "never" | "sometimes" | "often" | "everyday";

// ── Document interfaces ──────────────────────────────────────────────────

/**
 * /users/{uid}
 * Dart: lib/user_profile/domain/user_profile.dart — UserProfile
 * Note: "uid" is the document ID, not stored in the document data.
 */
export interface UserProfileDoc {
  name: string;
  firstName: string;
  lastName: string;
  displayName: string;
  dateOfBirth: FirebaseFirestore.Timestamp;
  gender: Gender;
  /** Authentication is phone-only */
  phoneNumber: string;
  countryCode: string;
  profileComplete: boolean;
  /** Optional profile/contact field */
  email: string;
  instagramHandle?: string | null;
  profilePrompts: ProfilePromptAnswer[];
  photoUrls: string[];
  photoThumbnailUrls: string[];
  photoPrompts: PhotoPromptAnswer[];
  city?: string | null;
  latitude?: number | null;
  longitude?: number | null;
  interestedInGenders: Gender[];
  minAgePreference: number;
  maxAgePreference: number;
  height?: number | null;
  occupation?: string | null;
  company?: string | null;
  education?: EducationLevel | null;
  religion?: Religion | null;
  languages: Language[];
  relationshipGoal?: RelationshipGoal | null;
  drinking?: DrinkingHabit | null;
  smoking?: SmokingHabit | null;
  workout?: WorkoutFrequency | null;
  diet?: DietaryPreference | null;
  children?: ChildrenStatus | null;
  paceMinSecsPerKm: number;
  paceMaxSecsPerKm: number;
  preferredDistances: PreferredDistance[];
  runningReasons: RunReason[];
  preferredRunTimes: PreferredRunTime[];
  runPreferencesVersion: number;
  prefsNewCatches: boolean;
  prefsMessages: boolean;
  prefsEventReminders: boolean;
  prefsRunStatusUpdates: boolean;
  prefsClubUpdates: boolean;
  prefsWeeklyDigest: boolean;
  prefsShowOnMap: boolean;
  /** Runtime — written by FcmService, not part of the profile form */
  fcmToken?: string;
  /** Safety/account lifecycle field written by account deletion flow */
  deleted?: boolean;
  deletedAt?: FirebaseFirestore.Timestamp;
  /**
   * Migration field; legacy documents may still only have parallel photo arrays
   */
  profilePhotos?: ProfilePhoto[];
}

/**
 * /publicProfiles/{uid}
 * Dart: lib/public_profile/domain/public_profile.dart — PublicProfile
 * Note: "uid" is the document ID, not stored in the document data.
 * Written exclusively by syncPublicProfile Cloud Function.
 */
export interface PublicProfileDoc {
  name: string;
  age: number;
  gender: Gender;
  profilePrompts: ProfilePromptAnswer[];
  photoUrls: string[];
  photoThumbnailUrls: string[];
  photoPrompts: PhotoPromptAnswer[];
  city?: string | null;
  height?: number | null;
  occupation?: string | null;
  company?: string | null;
  education?: EducationLevel | null;
  religion?: Religion | null;
  relationshipGoal?: RelationshipGoal | null;
  drinking?: DrinkingHabit | null;
  smoking?: SmokingHabit | null;
  workout?: WorkoutFrequency | null;
  diet?: DietaryPreference | null;
  children?: ChildrenStatus | null;
  paceMinSecsPerKm: number;
  paceMaxSecsPerKm: number;
  preferredDistances: PreferredDistance[];
  runningReasons: RunReason[];
  preferredRunTimes: PreferredRunTime[];
  runPreferencesVersion: number;
  languages?: Language[];
  /**
   * Migration field; legacy projections may still only have parallel photo
   * arrays
   */
  profilePhotos?: ProfilePhoto[];
}

/**
 * /clubs/{clubId}
 * Dart: lib/clubs/domain/club.dart — Club
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface ClubDoc {
  name: string;
  description: string;
  location: string;
  area: string;
  hostUserId: string;
  hostName: string;
  /** nullable in Firestore */
  hostAvatarUrl?: string | null;
  ownerUserId?: string | null;
  hostUserIds: string[];
  hostProfiles: ClubHostProfile[];
  createdAt: FirebaseFirestore.Timestamp;
  /** nullable in Firestore */
  imageUrl?: string | null;
  profileImageUrl?: string | null;
  tags: string[];
  memberCount: number;
  rating: number;
  reviewCount: number;
  /** nullable in Firestore */
  nextEventAt?: FirebaseFirestore.Timestamp | null;
  /** nullable in Firestore */
  nextEventLabel?: string | null;
  /** nullable in Firestore */
  instagramHandle?: string | null;
  /** nullable in Firestore */
  phoneNumber?: string | null;
  /** nullable in Firestore */
  email?: string | null;
  status: ClubLifecycleStatus;
  archived: boolean;
  archivedAt?: FirebaseFirestore.Timestamp | null;
  archiveReason?: string | null;
  hostDefaults: ClubHostDefaults;
}

/**
 * /clubMemberships/{membershipId}
 * Dart: lib/clubs/domain/club_membership.dart — ClubMembership
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface ClubMembershipDoc {
  clubId: string;
  uid: string;
  role: ClubMembershipRole;
  status: ClubMembershipStatus;
  pushNotificationsEnabled: boolean;
  joinedAt: FirebaseFirestore.Timestamp;
  leftAt?: FirebaseFirestore.Timestamp | null;
  deletedAt?: FirebaseFirestore.Timestamp | null;
}

/**
 * Dart: lib/events/domain/event_constraints.dart — EventConstraints
 */
export interface EventConstraints {
  minAge: number;
  maxAge: number;
  maxMen?: number | null;
  maxWomen?: number | null;
}

/**
 * /events/{eventId}
 * Dart: lib/events/domain/event.dart — Event
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface EventDoc {
  clubId: string;
  startTime: FirebaseFirestore.Timestamp;
  endTime: FirebaseFirestore.Timestamp;
  meetingPoint: string;
  meetingLocation?: EventMeetingLocation | null;
  /** nullable in Firestore */
  startingPointLat?: number | null;
  /** nullable in Firestore */
  startingPointLng?: number | null;
  /** nullable in Firestore */
  locationDetails?: string | null;
  photoUrl?: string | null;
  eventFormat: EventFormatSnapshot;
  distanceKm: number;
  pace: PaceLevel;
  capacityLimit: number;
  description: string;
  /**
   * legacy field name; amount in the event currency's minor unit. 0 = free
   * event
   */
  priceInPaise: number;
  currency: string;
  bookedCount?: number | null;
  checkedInCount?: number | null;
  waitlistedCount?: number | null;
  status: EventLifecycleStatus;
  cancelledAt?: FirebaseFirestore.Timestamp | null;
  cancellationReason?: string | null;
  constraints: EventConstraints;
  /**
   * Keys are Gender enum names: 'man', 'woman', 'nonBinary', 'other'.
   * Denormalized counts maintained atomically by Cloud Functions.
   */
  genderCounts: Record<string, number>;
  cohortCounts: Record<string, number>;
  waitlistedCohortCounts: Record<string, number>;
  /**
   * Production event-policy snapshot; legacy events may fall back to
   * capacityLimit, priceInPaise, and constraints
   */
  eventPolicy?: EventPolicyBundleDoc | null;
}

/**
 * /eventParticipations/{participationId}
 * Dart: lib/events/domain/event_participation.dart — EventParticipation
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface EventParticipationDoc {
  eventId: string;
  clubId: string;
  uid: string;
  status: EventParticipationStatus;
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt: FirebaseFirestore.Timestamp;
  signedUpAt?: FirebaseFirestore.Timestamp | null;
  waitlistedAt?: FirebaseFirestore.Timestamp | null;
  attendedAt?: FirebaseFirestore.Timestamp | null;
  cancelledAt?: FirebaseFirestore.Timestamp | null;
  deletedAt?: FirebaseFirestore.Timestamp | null;
  genderAtSignup?: Gender | null;
  cohortAtSignup?: string | null;
  paymentId?: string | null;
}

/**
 * /savedEvents/{savedEventId}
 * Dart: lib/events/domain/saved_event.dart — SavedEvent
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface SavedEventDoc {
  uid: string;
  eventId: string;
  savedAt: FirebaseFirestore.Timestamp;
}

/**
 * /payments/{paymentId}
 * Dart: lib/payments/domain/payment.dart — Payment
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface PaymentDoc {
  userId: string;
  orderId: string;
  paymentId: string;
  eventId: string;
  /** amount in the payment currency's minor unit */
  amount: number;
  currency: string;
  status: PaymentStatus;
  /** True when payment succeeded but sign-up failed due to a race or refund */
  signUpFailed: boolean;
  createdAt: FirebaseFirestore.Timestamp;
}

/**
 * /swipes/{userId}/outgoing/{targetId}
 * Dart: lib/swipes/domain/swipe.dart — Swipe
 */
export interface SwipeDoc {
  swiperId: string;
  targetId: string;
  eventId: string;
  direction: SwipeDirection;
  reactionTargetId?: string | null;
  reactionTargetType?: SwipeReactionTargetType | null;
  reactionTargetLabel?: string | null;
  reactionTargetPreview?: string | null;
  comment?: string | null;
  createdAt: FirebaseFirestore.Timestamp;
}

/**
 * /matches/{matchId}
 * Dart: lib/matches/domain/match.dart — Match
 * Note: "id" is the document ID, not stored in the document data.
 * Written exclusively by onSwipeCreated Cloud Function.
 */
export interface MatchDoc {
  user1Id: string;
  user2Id: string;
  eventIds: string[];
  createdAt: FirebaseFirestore.Timestamp;
  lastMessageAt?: FirebaseFirestore.Timestamp | null;
  lastMessagePreview?: string | null;
  lastMessageSenderId?: string | null;
  unreadCounts: Record<string, number>;
  status: MatchStatus;
  blockedBy?: string | null;
  blockedAt?: FirebaseFirestore.Timestamp | null;
  /** Always [user1Id, user2Id], used for Firestore arrayContains queries */
  participantIds: string[];
}

/**
 * /matches/{matchId}/messages/{messageId}
 * Dart: lib/chats/domain/chat_message.dart — ChatMessage
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface ChatMessageDoc {
  senderId: string;
  text: string;
  imageUrl?: string | null;
  sentAt?: FirebaseFirestore.Timestamp | null;
}

/**
 * /notifications/{uid}/items/{notificationId}
 * Dart: lib/notifications/domain/activity_notification.dart —
 * ActivityNotification
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface ActivityNotificationDoc {
  uid: string;
  type: ActivityNotificationType;
  title: string;
  body: string;
  createdAt: FirebaseFirestore.Timestamp;
  readAt?: FirebaseFirestore.Timestamp | null;
  matchId?: string | null;
  eventId?: string | null;
  clubId?: string | null;
  actorUid?: string | null;
  actorName?: string | null;
}

/**
 * /reviews/{reviewId}
 * Dart: lib/reviews/domain/review.dart — Review
 * Note: "id" is the document ID, not stored in the document data.
 * Written by review Cloud Functions using one deterministic document per
 * (eventId, reviewerUserId) pair.
 */
export interface ReviewDoc {
  clubId: string;
  /**
   * Required for new callable-created reviews; nullable only for legacy review
   * documents until migration.
   */
  eventId?: string | null;
  reviewerUserId: string;
  reviewerName: string;
  rating: number;
  comment: string;
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt?: FirebaseFirestore.Timestamp | null;
}

// ── Extra interfaces (no top-level Dart model) ────────────────────────────

/**
 * embedded club host profile
 * Stored inside clubs/{clubId}.hostProfiles for public multi-host display.
 */
export interface ClubHostProfile {
  uid: string;
  displayName: string;
  avatarUrl?: string | null;
  role: "owner" | "host";
}

/**
 * embedded profile prompt answer
 * Stored inside users/{uid}.profilePrompts and
 * publicProfiles/{uid}.profilePrompts.
 */
export interface ProfilePromptAnswer {
  promptId: string;
  prompt: string;
  answer: string;
}

/**
 * embedded photo prompt answer
 * Stored inside users/{uid}.photoPrompts and publicProfiles/{uid}.photoPrompts.
 */
export interface PhotoPromptAnswer {
  photoIndex: number;
  promptId: string;
  prompt: string;
  caption?: string | null;
}

/**
 * embedded event meeting location
 * Canonical meeting location stored inside events and accepted by event
 * callables during the legacy location-field migration.
 */
export interface EventMeetingLocation {
  name: string;
  address?: string | null;
  placeId?: string | null;
  latitude: number;
  longitude: number;
  notes?: string | null;
}

/**
 * embedded event format snapshot
 * Stored inside events/{eventId}.eventFormat so event success, health activity,
 * and host defaults share one activity taxonomy.
 */
export interface EventFormatSnapshot {
  version: number;
  activityKind:
    | "socialRun"
    | "running"
    | "walking"
    | "pickleball"
    | "padel"
    | "tennis"
    | "badminton"
    | "cycling"
    | "spinClass"
    | "yoga"
    | "strengthTraining"
    | "pubQuiz"
    | "barCrawl"
    | "dinner"
    | "singlesMixer"
    | "openActivity";
  interactionModel:
    | "pacePods"
    | "pairedRotations"
    | "teamRotations"
    | "seatedTable"
    | "freeFormMixer"
    | "hostLedProgram"
    | "openFormat";
  customActivityLabel?: string;
  defaultPlaybookId?: string;
  defaultModuleIds?: string[];
  activityDetails?: Record<string, unknown>;
}

/**
 * embedded club host defaults
 * Stored inside clubs/{clubId}.hostDefaults and copied into new event drafts.
 */
export interface ClubHostDefaults {
  primaryActivityKind?: EventFormatSnapshot["activityKind"];
  supportedActivityKinds?: EventFormatSnapshot["activityKind"][];
  eventPolicy: EventPolicyDefaults;
  eventSuccess: EventSuccessDefaults;
  eventSuccessByActivityKind?: Record<string, EventSuccessDefaults>;
}

/**
 * embedded event policy defaults
 * Stored inside clubs/{clubId}.hostDefaults.eventPolicy.
 */
export interface EventPolicyDefaults {
  admissionPreset: EventAdmissionDefaultPreset;
  minAge: number;
  maxAge: number;
  maxMen?: number | null;
  maxWomen?: number | null;
  dynamicPricingEnabled: boolean;
  dynamicPricingStepInPaise?: number | null;
  dynamicPricingMaxInPaise?: number | null;
  cancellationPolicyId: EventCancellationPolicyId;
}

/**
 * embedded event success structure config
 * Stored inside clubs/{clubId}.hostDefaults.eventSuccess.structureConfig and
 * eventSuccessPlans/{eventId}.structureConfig.
 */
export interface EventSuccessStructureConfig {
  unitKind: "wholeGroup" | "pods" | "pairs" | "teams" | "tables";
  unitSize: number;
  unitCount?: number | null;
  rotationIntervalMinutes?: number | null;
  revealCountdownSeconds: number;
}

/**
 * embedded event success defaults
 * Stored inside clubs/{clubId}.hostDefaults.eventSuccess.
 */
export interface EventSuccessDefaults {
  enabled: boolean;
  playbookId: string;
  selectedModuleIds: string[];
  structureConfig?: EventSuccessStructureConfig;
  hostGoal: string;
  wingmanRequestsEnabled: boolean;
  contextualOpenersEnabled: boolean;
  compatibilityAffectsRanking?: boolean;
  questionnaireConfig?:
    | { templateId: string; customTitle?: string
    | null; customQuestions?: unknown[] };
  attendeePrompt?: string | null;
}

/**
 * embedded profile photo moderation
 * Stored inside users/{uid}.profilePhotos and
 * publicProfiles/{uid}.profilePhotos.
 */
export interface ProfilePhotoModeration {
  status: "pending" | "approved" | "rejected";
  reason?: string | null;
  reviewedAt?: FirebaseFirestore.Timestamp | null;
}

/**
 * embedded profile photo
 * Canonical grouped profile photo object replacing parallel URL/prompt arrays.
 */
export interface ProfilePhoto {
  id: string;
  url: string;
  thumbnailUrl: string;
  storagePath: string;
  thumbnailStoragePath: string;
  prompt?: PhotoPromptAnswer | null;
  moderation?: ProfilePhotoModeration | null;
  position: number;
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt: FirebaseFirestore.Timestamp;
}

/**
 * embedded event policy snapshot
 * Stored inside events/{eventId}.eventPolicy for production booking, pricing,
 * cancellation, and settlement behavior.
 */
export interface EventPolicyBundleDoc {
  version: number;
  admission: EventPolicyAdmissionDoc;
  pricing: EventPolicyPricingDoc;
  cancellation: { policyId: "flexible" | "standard" | "strict" };
  settlement: { hostPayoutTiming: "afterEventCompletion" };
}

/**
 * embedded event policy admission
 * Nested inside events/{eventId}.eventPolicy.admission.
 */
export interface EventPolicyAdmissionDoc {
  format:
    | "open"
    | "inviteOnly"
    | "manualApproval"
    | "fixedCohortCaps"
    | "balancedRatio"
    | "membersOnly";
  capacityLimit: number;
  waitlistPolicy?: EventPolicyWaitlistDoc;
  inviteRequired?: boolean;
  membershipRequired?: boolean;
  manualApprovalRequired?: boolean;
  privateAccessPolicy?: EventPolicyPrivateAccessDoc;
  cohortCapacityLimits?: Record<string, number>;
  balancedRatioPolicy?: EventPolicyBalancedRatioDoc | null;
}

/**
 * embedded event policy private access
 * Public, non-secret invite metadata nested inside
 * events/{eventId}.eventPolicy.admission.privateAccessPolicy. Secret invite
 * codes live in eventPrivateAccess/{eventId}.
 */
export interface EventPolicyPrivateAccessDoc {
  mode: "none" | "inviteCode";
  inviteCodeHint: string | null;
  privateLinkEnabled: boolean;
}

/**
 * embedded event policy waitlist
 * Nested inside events/{eventId}.eventPolicy.admission.waitlistPolicy.
 */
export interface EventPolicyWaitlistDoc {
  mode:
    | "disabled"
    | "rankedOffer"
    | "broadcastFirstComeFirstServed"
    | "manualReview";
  offerWindowMinutes: number;
}

/**
 * embedded event policy balanced ratio
 * Nested inside events/{eventId}.eventPolicy.admission.balancedRatioPolicy.
 */
export interface EventPolicyBalancedRatioDoc {
  leftCohortId: string;
  rightCohortId: string;
  maxSkew: number;
  openingBufferPerCohort: number;
  outOfRatioCohortPolicy:
    | "admitWithinGeneralCapacity"
    | "waitlist"
    | "manualReview"
    | "reject";
}

/**
 * embedded event policy pricing
 * Nested inside events/{eventId}.eventPolicy.pricing.
 */
export interface EventPolicyPricingDoc {
  basePriceInPaise: number;
  cohortAdjustmentsInPaise?: Record<string, number>;
  demandPricingRules?: EventPolicyDemandPricingRuleDoc[];
}

/**
 * embedded event policy demand pricing rule
 * Nested inside events/{eventId}.eventPolicy.pricing.demandPricingRules.
 */
export interface EventPolicyDemandPricingRuleDoc {
  pricedCohortId: string;
  balancingCohortId: string;
  stepAdjustmentInPaise: number;
  maxAdjustmentInPaise: number;
  freeSkew: number;
  demandStep: number;
}

/**
 * /eventPrivateAccess/{eventId}
 * Host-private invite material created by createEvent for invite-only events.
 */
export interface EventPrivateAccessDoc {
  eventId: string;
  clubId: string;
  inviteCode: string;
  createdAt: FirebaseFirestore.Timestamp;
}

/**
 * /blocks/{blockerUserId}__{blockedUserId}
 * Server-enforced safety edge. Either direction blocks shared dating surfaces.
 */
export interface BlockDoc {
  blockerUserId: string;
  blockedUserId: string;
  createdAt: FirebaseFirestore.Timestamp;
  source: "profile" | "chat" | "match" | "support";
  reasonCode?: string;
}

/**
 * /reports/{reportId}
 * Server-owned safety report for abuse/moderation review.
 */
export interface ReportDoc {
  reporterUserId: string;
  targetUserId: string;
  createdAt: FirebaseFirestore.Timestamp;
  source: "profile" | "chat" | "match" | "support";
  status: "open" | "reviewed" | "dismissed";
  reasonCode?: string;
  contextId?: string;
  notes?: string;
}

/**
 * /moderationFlags/{flagId}
 * Server-owned moderation ticket created when auto-moderation flags content.
 */
export interface ModerationFlagDoc {
  targetUserId: string;
  flagType: "explicit_photo" | "banned_text" | "underage_content";
  source:
    | "profile_photo"
    | "club_image"
    | "chat_message"
    | "user_bio"
    | "club_description"
    | "review_comment";
  status: "pending" | "reviewed" | "dismissed";
  createdAt: FirebaseFirestore.Timestamp;
  reviewedAt?: FirebaseFirestore.Timestamp;
  contextId?: string;
  context?: string;
  safeSearchResults?: Record<string, string>;
}

