/**
 * Firestore document interfaces for Cloud Functions.
 *
 * AUTO-GENERATED by tool/generate_firestore_types.dart
 * DO NOT EDIT DIRECTLY.
 *
 * To update: dart tool/generate_firestore_types.dart
 *
 * These mirror the Dart freezed models in lib/<feature>/domain/<Model>.dart.
 * Enum values match what Dart's json_serializable serialises by default
 * (enum member name, camelCase — e.g. DrinkingHabit.socially → "socially").
 *
 * Fields marked with @JsonKey(includeToJson: false) in Dart are the
 * document ID and are NOT stored inside the document data.
 *
 * Timestamps are stored as Firestore timestamps in the DB. In admin SDK
 * code, use FirebaseFirestore.Timestamp and FieldValue.serverTimestamp()
 * to write.
 */

// FirebaseFirestore.Timestamp is available globally via
// @google-cloud/firestore, a transitive dependency of firebase-admin.

// ── Shared enum types ────────────────────────────────────────────────────

export type ChildrenStatus =
  | "dontHave"
  | "haveWantMore"
  | "haveNoMore"
  | "wantSomeday"
  | "dontWant";

export type DietaryPreference =
  | "omnivore"
  | "vegetarian"
  | "vegan"
  | "jain"
  | "other";

export type DrinkingHabit = "never" | "socially" | "often";

export type EducationLevel =
  | "highSchool"
  | "someCollege"
  | "bachelors"
  | "masters"
  | "phd"
  | "tradeSchool"
  | "other";

export type Gender = "man" | "woman" | "nonBinary" | "other";

export type IndianCity =
  | "mumbai"
  | "delhi"
  | "bangalore"
  | "hyderabad"
  | "chennai"
  | "kolkata"
  | "pune"
  | "ahmedabad"
  | "indore";

export type Language =
  | "english"
  | "hindi"
  | "marathi"
  | "tamil"
  | "telugu"
  | "kannada"
  | "bengali"
  | "gujarati"
  | "punjabi"
  | "malayalam"
  | "odia"
  | "other";

export type MatchStatus = "active" | "blocked";

export type PaceLevel = "easy" | "moderate" | "fast" | "competitive";

export type PaymentStatus = "pending" | "completed" | "failed" | "refunded";

export type PreferredDistance = "fiveK" | "tenK" | "halfMarathon" | "marathon";

export type RelationshipGoal =
  | "relationship"
  | "casual"
  | "marriage"
  | "friendship"
  | "unsure";

export type Religion =
  | "hindu"
  | "muslim"
  | "christian"
  | "sikh"
  | "jain"
  | "buddhist"
  | "other"
  | "nonReligious";

export type RunReason =
  | "fitness"
  | "community"
  | "mindfulness"
  | "challenge"
  | "weightLoss"
  | "raceTraining"
  | "social";

export type SmokingHabit = "never" | "occasionally" | "often";

export type SwipeDirection = "like" | "pass";

export type WorkoutFrequency = "never" | "sometimes" | "often" | "everyday";

// ── Document interfaces ──────────────────────────────────────────────────

/**
 * /users/{uid}
 * Dart: lib/user_profile/domain/user_profile.dart — UserProfile
 * Note: "uid" is the document ID, not stored in the document data.
 */
export interface UserProfileDoc {
  name: string;
  dateOfBirth: FirebaseFirestore.Timestamp;
  gender: Gender;
  /** Authentication is phone-only */
  phoneNumber: string;
  profileComplete: boolean;
  /** Optional profile/contact field */
  email: string;
  bio: string;
  instagramHandle?: string | null;
  photoUrls: string[];
  city?: IndianCity | null;
  latitude?: number | null;
  longitude?: number | null;
  joinedRunClubIds: string[];
  savedRunIds: string[];
  interestedInGenders: Gender[];
  minAgePreference: number;
  maxAgePreference: number;
  height?: number | null;
  occupation?: string | null;
  company?: string | null;
  education?: EducationLevel | null;
  religion?: Religion | null;
  languages: Language[];
  relationshipGoal?: RelationshipGoal | null;
  drinking?: DrinkingHabit | null;
  smoking?: SmokingHabit | null;
  workout?: WorkoutFrequency | null;
  diet?: DietaryPreference | null;
  children?: ChildrenStatus | null;
  paceMinSecsPerKm: number;
  paceMaxSecsPerKm: number;
  preferredDistances: PreferredDistance[];
  runningReasons: RunReason[];
  prefsNewCatches: boolean;
  prefsRunReminders: boolean;
  prefsWeeklyDigest: boolean;
  prefsShowOnMap: boolean;
  /** Runtime — written by FcmService, not part of the profile form */
  fcmToken?: string;
  /** Safety/account lifecycle field written by account deletion flow */
  deleted?: boolean;
  deletedAt?: FirebaseFirestore.Timestamp;
}

/**
 * /publicProfiles/{uid}
 * Dart: lib/public_profile/domain/public_profile.dart — PublicProfile
 * Note: "uid" is the document ID, not stored in the document data.
 * Written exclusively by syncPublicProfile Cloud Function.
 */
export interface PublicProfileDoc {
  name: string;
  age: number;
  bio: string;
  gender: Gender;
  photoUrls: string[];
  city?: IndianCity | null;
  latitude?: number | null;
  longitude?: number | null;
  height?: number | null;
  occupation?: string | null;
  company?: string | null;
  education?: EducationLevel | null;
  religion?: Religion | null;
  relationshipGoal?: RelationshipGoal | null;
  drinking?: DrinkingHabit | null;
  smoking?: SmokingHabit | null;
  workout?: WorkoutFrequency | null;
  diet?: DietaryPreference | null;
  children?: ChildrenStatus | null;
  paceMinSecsPerKm: number;
  paceMaxSecsPerKm: number;
  preferredDistances: PreferredDistance[];
  runningReasons: RunReason[];
  languages?: Language[];
}

/**
 * /runClubs/{clubId}
 * Dart: lib/run_clubs/domain/run_club.dart — RunClub
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface RunClubDoc {
  name: string;
  description: string;
  location: IndianCity;
  area: string;
  hostUserId: string;
  hostName: string;
  /** nullable in Firestore */
  hostAvatarUrl?: string | null;
  createdAt: FirebaseFirestore.Timestamp;
  /** nullable in Firestore */
  imageUrl?: string | null;
  tags: string[];
  memberUserIds: string[];
  memberCount: number;
  rating: number;
  reviewCount: number;
  /** nullable in Firestore */
  nextRunAt?: FirebaseFirestore.Timestamp | null;
  /** nullable in Firestore */
  nextRunLabel?: string | null;
  /** nullable in Firestore */
  instagramHandle?: string | null;
  /** nullable in Firestore */
  phoneNumber?: string | null;
  /** nullable in Firestore */
  email?: string | null;
}

/**
 * Dart: lib/runs/domain/run_constraints.dart — RunConstraints
 */
export interface RunConstraints {
  minAge: number;
  maxAge: number;
  maxMen?: number | null;
  maxWomen?: number | null;
}

/**
 * /runs/{runId}
 * Dart: lib/runs/domain/run.dart — Run
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface RunDoc {
  runClubId: string;
  startTime: FirebaseFirestore.Timestamp;
  endTime: FirebaseFirestore.Timestamp;
  meetingPoint: string;
  /** nullable in Firestore */
  startingPointLat?: number | null;
  /** nullable in Firestore */
  startingPointLng?: number | null;
  /** nullable in Firestore */
  locationDetails?: string | null;
  distanceKm: number;
  pace: PaceLevel;
  capacityLimit: number;
  description: string;
  /** in paise (INR subunit). 0 = free run */
  priceInPaise: number;
  signedUpUserIds: string[];
  attendedUserIds: string[];
  waitlistUserIds: string[];
  constraints: RunConstraints;
  /** Keys are Gender enum names: 'man', 'woman', 'nonBinary', 'other'. Denormalized counts maintained atomically by Cloud Functions. */
  genderCounts: Record<string, number>;
}

/**
 * /payments/{paymentId}
 * Dart: lib/payments/domain/payment.dart — Payment
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface PaymentDoc {
  userId: string;
  orderId: string;
  paymentId: string;
  runId: string;
  /** in paise */
  amount: number;
  currency: string;
  status: PaymentStatus;
  /** True when payment succeeded but sign-up failed due to a race or refund */
  signUpFailed: boolean;
  createdAt: FirebaseFirestore.Timestamp;
}

/**
 * /swipes/{userId}/outgoing/{targetId}
 * Dart: lib/swipes/domain/swipe.dart — Swipe
 */
export interface SwipeDoc {
  swiperId: string;
  targetId: string;
  runId: string;
  direction: SwipeDirection;
  createdAt: FirebaseFirestore.Timestamp;
}

/**
 * /matches/{matchId}
 * Dart: lib/matches/domain/match.dart — Match
 * Note: "id" is the document ID, not stored in the document data.
 * Written exclusively by onSwipeCreated Cloud Function.
 */
export interface MatchDoc {
  user1Id: string;
  user2Id: string;
  runId: string;
  createdAt: FirebaseFirestore.Timestamp;
  lastMessageAt?: FirebaseFirestore.Timestamp | null;
  lastMessagePreview?: string | null;
  lastMessageSenderId?: string | null;
  unreadCounts: Record<string, number>;
  status: MatchStatus;
  blockedBy?: string | null;
  blockedAt?: FirebaseFirestore.Timestamp | null;
  /** Always [user1Id, user2Id], used for Firestore arrayContains queries */
  participantIds: string[];
}

/**
 * /chats/{matchId}/messages/{messageId}
 * Dart: lib/chats/domain/chat_message.dart — ChatMessage
 * Note: "id" is the document ID, not stored in the document data.
 */
export interface ChatMessageDoc {
  senderId: string;
  text: string;
  imageUrl?: string | null;
  sentAt: FirebaseFirestore.Timestamp;
}

/**
 * /reviews/{reviewId}
 * Dart: lib/reviews/domain/review.dart — Review
 * Note: "id" is the document ID, not stored in the document data.
 * The current client uses one deterministic review document per (runClubId, reviewerUserId) pair.
 */
export interface ReviewDoc {
  runClubId: string;
  /** optional — not all reviews are linked to a specific run */
  runId?: string | null;
  reviewerUserId: string;
  reviewerName: string;
  rating: number;
  comment: string;
  createdAt: FirebaseFirestore.Timestamp;
  updatedAt?: FirebaseFirestore.Timestamp | null;
}

// ── Server-only interfaces (no Dart model) ────────────────────────────────

/**
 * /blocks/{blockerUserId}__{blockedUserId}
 * Server-enforced safety edge. Either direction blocks shared dating surfaces.
 */
export interface BlockDoc {
  blockerUserId: string;
  blockedUserId: string;
  createdAt: FirebaseFirestore.Timestamp;
  source: "profile" | "chat" | "match" | "support";
  reasonCode?: string;
}

/**
 * /reports/{reportId}
 * Server-owned safety report for abuse/moderation review.
 */
export interface ReportDoc {
  reporterUserId: string;
  targetUserId: string;
  createdAt: FirebaseFirestore.Timestamp;
  source: "profile" | "chat" | "match" | "support";
  status: "open" | "reviewed" | "dismissed";
  reasonCode?: string;
  contextId?: string;
  notes?: string;
}

/**
 * /moderationFlags/{flagId}
 * Server-owned moderation ticket created when auto-moderation flags content.
 */
export interface ModerationFlagDoc {
  targetUserId: string;
  flagType: "explicit_photo" | "banned_text" | "underage_content";
  source: "profile_photo" | "club_image" | "chat_message" | "user_bio" | "club_description" | "review_comment";
  status: "pending" | "reviewed" | "dismissed";
  createdAt: FirebaseFirestore.Timestamp;
  reviewedAt?: FirebaseFirestore.Timestamp;
  contextId?: string;
  context?: string;
  safeSearchResults?: Record<string, string>;
}

