export const eventMessagingCopy = {
  withdrawalScope: "Turn off Catch text updates for this event. Your registration and event access will stay the same.",
  withdrawalSaved: "Text updates for this event are off.",
  withdrawalChanged: "Text updates are currently on. Your preference changed elsewhere; tap again if you want to turn them off.",
  title: "Event text updates",
  loading: "Loading your text preferences…",
  loadFailed: "Your text preference could not be loaded.",
  turnOn: "Turn on event texts",
  turnOff: "Turn off event texts",
  saving: "Saving…",
  retry: "Retry the change",
  refresh: "Refresh preference",
  enabled: "Event texts are on.",
  disabled: "Event texts are off.",
  expired: "Text updates for this event have ended.",
  phonePrefix: "For your verified number ending in",
  unavailable: "Text updates are currently unavailable.",
  savedOn: "Event texts are now on.",
  savedOff: "Event texts are now off.",
  changed: "Your preference changed elsewhere. Review it before trying again.",
  rejected: "This change could not be saved. Refresh your preference before trying again.",
  uncertain: "We could not confirm the change. Retry to check whether it was saved.",
} as const;

export const eventWhatsappMessagingCopy = {
  ...eventMessagingCopy,
  title: "Event WhatsApp updates",
  loading: "Loading your WhatsApp preference…",
  loadFailed: "Your WhatsApp preference could not be loaded.",
  withdrawalScope: "Turn off WhatsApp updates from the organizer for this event. Your registration and event access will stay the same.",
  withdrawalSaved: "WhatsApp updates for this event are off.",
  withdrawalChanged: "Your WhatsApp preference changed elsewhere. Tap again if you want to turn updates off.",
  turnOn: "Turn on event WhatsApp updates",
  turnOff: "Turn off WhatsApp updates",
  enabled: "Event WhatsApp updates are on.",
  disabled: "Event WhatsApp updates are off.",
  expired: "WhatsApp updates for this event have ended.",
  unavailable: "WhatsApp updates are currently unavailable.",
  savedOn: "Event WhatsApp updates are now on.",
  savedOff: "Event WhatsApp updates are now off.",
} as const;
