export const eventRuntimeCopy = {
  brand: "Catch event mode",
  brandWord: "Catch",
  demoEventTitle: "Courtyard Social",
  phoneKicker: "You are on the guest list",
  phoneTitle: "Check in and make this room easier to meet.",
  phoneBody: "No download. Verify the phone number used for your booking to open tonight's live event tools.",
  phoneLabel: "Mobile number",
  phonePlaceholder: "+91 98765 43210",
  sendCode: "Text me a code",
  sendingCode: "Sending code...",
  otpKicker: "One quick check",
  otpTitle: "Enter the 6-digit code",
  otpBody: "We sent it to the number you entered. Catch uses it only to match you to this event's guest list.",
  otpLabel: "Verification code",
  confirmCode: "Open event mode",
  confirmingCode: "Checking code...",
  profileKicker: "Set up event mode",
  profileTitle: "A couple of details for tonight",
  profileBody: "Your name and one format-specific answer prepare event mode. Preference answers remain optional and can be skipped without losing live tools.",
  preEventTitle: "Help the room get ready",
  preEventBody: "One event-only answer helps the Host prepare tonight before anyone reaches the door.",
  paceBandLabel: "My comfortable pace",
  skillBandLabel: "My current playing level",
  dietaryAndSeatingLabel: "Dietary or seating needs",
  dietaryAndSeatingPlaceholder: "For example: vegetarian, allergy, step-free seat, or seat me with my arrival group",
  teamNameLabel: "Team name or arrival group",
  teamNamePlaceholder: "For example: The Late Entries",
  preEventSensitiveConsent: "Use this event-only answer to prepare groups, introductions, or Host logistics for tonight.",
  displayNameLabel: "First name or event name",
  genderLabel: "I describe myself as",
  interestedLabel: "I would like to meet",
  preferenceOptIn: "Optionally use gender and who-I-want-to-meet answers to improve preference-aware suggestions.",
  preferenceSkipped: "You will receive neutral introductions, groups, and rotations. You can still use First Hello and ask the host for an introduction.",
  sensitiveConsent: "Use my gender and who-I-want-to-meet answers to power this event's introductions and group suggestions.",
  prefillConsent: "Save these answers as a private draft if I later join Catch. This does not create a public profile.",
  continueAction: "Enter event mode",
  savingProfile: "Preparing event mode...",
  approvalKicker: "Request received",
  approvalTitle: "The host needs to approve this number",
  approvalBody: "You are not matched to an imported guest-list row yet. Ask the host to approve the request, then refresh here.",
  refreshAction: "Check again",
  venueKicker: "Confirm you are here",
  venueTitle: "Scan the Host's live QR",
  venueBody: "The shared event link opens this companion but cannot check you in. Scan the current QR on the Host's screen at the venue.",
  runtimeEyebrow: "Live at your event",
  checkedIn: "Checked in",
  checkedInCount: (count: number) => `${count} checked in`,
  runOfShowTitle: "Tonight's run of show",
  movementTitle: "Route and pace groups",
  mappedRoute: (count: number) =>
    `${count} mapped route ${count === 1 ? "point" : "points"}`,
  paceTarget: (secondsPerKm: number) => {
    const minutes = Math.floor(secondsPerKm / 60);
    const seconds = `${secondsPerKm % 60}`.padStart(2, "0");
    return `${minutes}:${seconds}/km`;
  },
  movingGroupTitle: "Find the moving group",
  movingGroupBody: "This fresh Host or route-operator position is shown against the saved route. Catch never shares attendee locations.",
  movingGroupMapLabel: "Saved route and current moving-group position",
  movingGroupMapHelp: "Route schematic — use the next published stop for arrival guidance.",
  movingGroupScheduledBody: "No fresh Host position is available. Follow the next published stop as scheduled guidance and confirm with the Host when you arrive.",
  movingGroupUpdated: (recordedAtMillis: number) =>
    `Updated ${new Intl.DateTimeFormat(undefined, {
      hour: "numeric",
      minute: "2-digit",
    }).format(new Date(recordedAtMillis))}`,
  nextPublishedStop: (title: string) => `Next published stop: ${title}`,
  shareTitle: "Bring someone along",
  shareBody: "Share your personal event link. Catch can see when it is opened. Registration and check-in credit appears only when Catch or the booking provider can reconcile that same link.",
  shareAction: "Share this event",
  shareLinkLabel: "Attendee share",
  sharePreparing: "Preparing your link...",
  shareRetry: "Try preparing my link again",
  shareNotReady: "Your personal link is still being prepared. Try again in a moment.",
  shareOpened: "Share options opened.",
  shareCopied: "Your personal event link is copied.",
  shareCancelled: "Sharing cancelled.",
  shareText: (eventTitle: string) => `Join me at ${eventTitle}.`,
  shareManual: (shareUrl: string) => `Copy your personal event link: ${shareUrl}`,
  assignmentTitle: "Your next move",
  standingsTitle: "Live standings",
  assignmentEmpty: "The host has not released a table, pod, or rotation yet. Keep this page open—updates arrive live.",
  roomMapTitle: "Where to go",
  roomMapSubtitle: "An outline is your assigned place. A filled marker means the host confirmed you there.",
  roomMapAssigned: "Assigned",
  roomMapConfirmed: "Host confirmed",
  roomMapSelf: "You",
  revealWaiting: "The room is getting its next assignment. Keep this page open for the reveal.",
  hostPromptTitle: "From your host",
  lateArrivalTitle: "Your next round",
  compatibilityTitle: "Tune your introductions",
  compatibilityBody: "Pick one answer per question. These are lightweight event signals, not a dating profile.",
  compatibilitySave: "Save answers",
  compatibilitySaved: "Answers saved",
  firstHelloTitle: "First Hello",
  firstHelloBody: "Get one low-pressure person and a conversation starter. Complete it to confirm arrival.",
  firstHelloStart: "Give me a First Hello",
  firstHelloStarting: "Finding someone...",
  firstHelloComplete: "We said hello",
  wingmanTitle: "Ask the host for an intro",
  wingmanBody: "Choose someone and privately ask the host to help you meet. The other attendee is not notified by Catch.",
  wingmanSelect: "Choose an attendee",
  wingmanSubmit: "Ask for an intro",
  wingmanWithdraw: "Withdraw request",
  wingmanEmpty: "No eligible attendees are available yet.",
  conversationTitle: "Who did you actually talk to?",
  conversationBody: "Choose everyone you remember speaking with. Suggested people are people the event assigned you to; they are not selected unless this event uses the configurable preselection mode.",
  conversationSuggested: "Suggested",
  conversationSave: "Save who I spoke with",
  conversationSkip: "Skip for now",
  conversationLoading: "Preparing the event roster...",
  conversationEmpty: "No other checked-in attendees are available.",
  conversationPrivacy: "Your choices stay private to you and Catch. The host receives counts and exclusion patterns, never who named whom.",
  conversationSaved: "Your conversation check is saved.",
  conversationSkipped: "Conversation check skipped for now.",
  feedbackTitle: "A private read on the event",
  feedbackBody: "This goes to Catch's event-quality and safety systems. Hosts receive aggregate coaching, not your private note.",
  welcomeRating: "How welcome did you feel?",
  structureRating: "How useful was the event structure?",
  peopleMet: "How many new people did you meet?",
  safetyConcern: "I want Catch's safety team to review a concern.",
  privateNote: "Private note (optional)",
  feedbackSave: "Save private feedback",
  feedbackSaved: "Your feedback is saved.",
  privacyNote: "Event mode does not create a Catch dating profile, matching inbox, or chat. The host can see attendance and host-help requests.",
  unavailableTitle: "This event mode link is unavailable",
  unavailableBody: "Check the QR code or ask the host for a fresh link.",
  helpAction: "Open help and safety",
  invalidPhone: "Enter a mobile number with country code, such as +91 98765 43210.",
  invalidCode: "Enter the 6-digit code from the text message.",
  missingName: "Tell us what the host should call you.",
  missingSensitiveConsent: "Confirm that Catch may use these event-only answers before continuing.",
  missingInterests: "Choose at least one kind of person you would like to meet.",
  missingPreEventAnswer: "Complete tonight's event question before continuing.",
  genericError: "Something did not go through. Try again or ask the host for help.",
  eventUnavailable: "This event mode link is no longer accepting check-ins.",
  verificationExpired: "That code expired. Request a new one.",
  tooManyRequests: "Too many attempts. Wait a few minutes before trying again.",
} as const;

export const eventRuntimePaceBandOptions = [
  {id: "competitive", label: "Competitive · around 5:00/km or faster"},
  {id: "fast", label: "Fast · around 5:00–6:00/km"},
  {id: "moderate", label: "Moderate · around 6:00–7:00/km"},
  {id: "easy", label: "Easy · 7:00/km or gentler"},
] as const;

export const eventRuntimeSkillBandOptions = [
  {id: "beginner", label: "Beginner"},
  {id: "intermediate", label: "Intermediate"},
  {id: "advanced", label: "Advanced"},
] as const;

export const eventRuntimeSocialMissionCopy = {
  titles: {
    light: "Easy start",
    personal: "A little more personal",
    reflective: "One level deeper",
  },
  labels: {
    light: "Light disclosure",
    personal: "Personal disclosure",
    reflective: "Reflective disclosure",
  },
  prompts: {
    "pacePods.light": "Ask someone what route, cafe, or park they would do again.",
    "pairedRotations.light": "Ask your next partner what shot they are trying to improve.",
    "teamRotations.light": "Ask which round they wanted more questions from.",
    "seatedTable.light": "Ask what dish they would order again.",
    "freeFormMixer.light": "Ask what answer from tonight surprised them.",
    "hostLedProgram.light": "Ask what made them say yes to this event.",
    "openFormat.light": "Ask what made them say yes to this event.",
    "shared.personal": "Take turns sharing something you changed your mind about recently and what shifted it.",
    "shared.reflective": "Take turns answering: what do you hope the people close to you understand about you?",
  },
} as const;

export const eventRuntimeQuestionnairePacks = {
  balanced: {
    title: "A little about tonight",
    questions: [
      {id: "event_energy", prompt: "Tonight I'm most up for", options: [
        {id: "event_energy_easy_conversation", label: "Easy conversation"},
        {id: "event_energy_playful_competition", label: "Playful competition"},
        {id: "event_energy_quiet_chemistry", label: "Quiet chemistry"},
        {id: "event_energy_new_people", label: "Meeting a few new people"},
      ]},
      {id: "first_conversation", prompt: "My best first conversation starts with", options: [
        {id: "first_conversation_activity", label: "A shared activity"},
        {id: "first_conversation_question", label: "A thoughtful question"},
        {id: "first_conversation_joke", label: "A joke"},
        {id: "first_conversation_recommendation", label: "A practical recommendation"},
      ]},
      {id: "shared_connection", prompt: "I usually connect over", options: [
        {id: "shared_connection_movement", label: "Movement"},
        {id: "shared_connection_places", label: "Food and places"},
        {id: "shared_connection_ideas", label: "Ideas and trivia"},
        {id: "shared_connection_future_plans", label: "Future plans"},
      ]},
      {id: "after_event", prompt: "After a good event I'd rather", options: [
        {id: "after_event_coffee", label: "Grab coffee"},
        {id: "after_event_activity", label: "Plan another activity"},
        {id: "after_event_text_first", label: "Text first"},
        {id: "after_event_keep_casual", label: "Keep it casual"},
      ]},
    ],
  },
  flirty: {
    title: "Find your energy",
    questions: [
      {id: "flirty_energy", prompt: "The kind of spark I enjoy is", options: [
        {id: "flirty_energy_banter", label: "Quick banter"},
        {id: "flirty_energy_slow_burn", label: "A slow burn"},
        {id: "flirty_energy_playful_challenge", label: "A playful challenge"},
      ]},
      {id: "flirty_first_move", prompt: "I respond best when someone", options: [
        {id: "flirty_first_move_direct", label: "Is direct"},
        {id: "flirty_first_move_witty", label: "Makes me laugh"},
        {id: "flirty_first_move_curious", label: "Asks something real"},
      ]},
    ],
  },
  earnest: {
    title: "What feels good tonight",
    questions: [
      {id: "earnest_connection", prompt: "I feel most connected when conversation is about", options: [
        {id: "earnest_connection_values", label: "Values"},
        {id: "earnest_connection_family", label: "Family and community"},
        {id: "earnest_connection_growth", label: "Growth and goals"},
      ]},
      {id: "earnest_date_energy", prompt: "A good first follow-up would feel", options: [
        {id: "earnest_date_energy_calm", label: "Calm and thoughtful"},
        {id: "earnest_date_energy_active", label: "Active and easygoing"},
        {id: "earnest_date_energy_deep", label: "Unhurried and deep"},
      ]},
    ],
  },
  intentional: {
    title: "Your pace",
    questions: [
      {id: "intentional_pace", prompt: "I prefer new connections to move", options: [
        {id: "intentional_pace_slow", label: "Slowly"},
        {id: "intentional_pace_natural", label: "Naturally"},
        {id: "intentional_pace_clear", label: "With clear intent"},
      ]},
      {id: "intentional_life_fit", prompt: "Compatibility means sharing", options: [
        {id: "intentional_life_fit_rhythm", label: "A similar life rhythm"},
        {id: "intentional_life_fit_values", label: "Core values"},
        {id: "intentional_life_fit_curiosity", label: "Curiosity and respect"},
      ]},
    ],
  },
} as const;

export const eventRuntimeGenderOptions = [
  {id: "woman", label: "Woman"},
  {id: "man", label: "Man"},
  {id: "nonBinary", label: "Non-binary"},
  {id: "other", label: "Another identity"},
] as const;
