export const eventRehearsalCopy = {
  brand: "Catch",
  brandWord: "catch",
  practiceBanner: "Practice mode · This phone controls a synthetic guest only",
  loading: "Opening the practice room…",
  loadingTitle: "Joining the dress rehearsal",
  unavailableKicker: "Practice link",
  unavailableTitle: "This rehearsal is unavailable",
  unavailableBody:
    "The link may have expired, been replaced, or hit a simulated connection issue.",
  retry: "Try again",
  liveKicker: "Live rehearsal",
  completeKicker: "Practice complete",
  locationSeparator: " · ",
  virtualTimePrefix: "Virtual time",
  runOfShowTitle: "Practice run of show",
  routeTitle: "Synthetic movement guidance",
  itineraryOffset: (minutes: number) => `+${minutes} min`,
  routePoints: (count: number) =>
    `${count} saved route ${count === 1 ? "point" : "points"}`,
  routeMapLabel: "Saved practice route and synthetic operator position",
  routeMapHelp:
    "Practice schematic · This position is deterministic synthetic data.",
  trackerRole: (role: "host" | "operator") =>
    role === "host" ? "Synthetic Host" : "Synthetic route operator",
  promptTitle: "Your practice prompt",
  actionsTitle: "Try the guest controls",
  actionsBody:
    "Every action changes only this synthetic guest and appears on the Host practice screen.",
  checkedIn: "Check in",
  confirmArrival: "Confirm arrival",
  optOut: "Opt out of social activities",
  optIn: "Opt back in",
  askForHelp: "Ask the Host for help",
  completePrompt: "Mark prompt complete",
  actionPending: "Updating practice room…",
  actionSuccess: "The Host practice screen has your update.",
  refreshNotice: "Waiting for the Host to advance the virtual event.",
  waitingTitle: "Waiting for the Host",
  waitingBody:
    "Keep this practice phone open. Guest controls appear when the Host starts the virtual event.",
  completeTitle: "The rehearsal has ended",
  completeBody:
    "You can leave this phone open while the Host reviews the deterministic recap.",
  optedOutNotice: "This synthetic guest is opted out of social activities.",
  helpRequestedNotice: "The Host practice screen shows a help request.",
  promptCompletedNotice: "The practice prompt is complete.",
  statusLabels: {
    expected: "Expected",
    present: "Present",
    late: "Late arrival",
    noShow: "No-show",
    departed: "Left early",
    returned: "Returned",
    disconnected: "Connection lost",
    walkIn: "Walk-in",
    ambiguousClaim: "Identity needs Host review",
  },
  momentTitles: {
    welcome: "Welcome to the practice room",
    checkIn: "Arrive and check in",
    firstHello: "Make the first hello easy",
    assignment: "Find your practice group",
    rotation: "Move to the next round",
    pause: "The Host has paused the room",
    reveal: "The reveal is beginning",
    afterglow: "Close the room thoughtfully",
    complete: "Practice complete",
  },
  momentBodies: {
    welcome: "The Host is preparing the rehearsal. Nothing here reaches a real event.",
    checkIn: "Use the arrival control so the Host can see this synthetic guest enter.",
    firstHello: "Follow the prompt and test how the guest guidance feels on a phone.",
    assignment: "The Host can now practice placing late, new, or unresolved guests.",
    rotation: "Keep this phone open while the Host advances the virtual playbook.",
    pause: "Your place is preserved. The Host can recover and resume when ready.",
    reveal: "This is a safe place to test interruption, reduced motion, and recovery.",
    afterglow: "Try opt-out, help, and completion states before the run closes.",
    complete: "The Host can reset the same seed, fork the setup, or copy a reproduction.",
  },
  faultNotices: {
    latency: "QA simulation: Host actions are intentionally delayed.",
    oneShotFailure: "QA simulation: the next Host action fails once and can be retried safely.",
    listenerDisconnect: "QA simulation: guest refreshes are temporarily disconnected.",
    staleRevision: "QA simulation: the next Host action reports a stale revision.",
    duplicateDelivery: "QA simulation: duplicate delivery is being deduplicated.",
    legacyFixture: "QA simulation: this view is exercising legacy-fixture compatibility.",
    reducedMotion: "QA simulation: motion is reduced for this guest view.",
    lowBandwidth: "QA simulation: guest updates arrive on a slower cadence.",
  },
} as const;
