export const publicFormsCopy = {
  brand: "Catch Forms",
  brandWord: "catch",
  loading: "Opening form",
  unavailableTitle: "This form is unavailable",
  unavailableBody: "The organizer may have paused, closed, or filled this form.",
  identityKicker: "Secure response",
  identityTitle: "Verify before continuing",
  identityBody: "Verify your identity to continue. Verification does not make your profile public or sign you up for WhatsApp messages.",
  phoneLabel: "Mobile number",
  phonePlaceholder: "+91 98765 43210",
  sendCode: "Send code",
  sendingCode: "Sending code",
  codeLabel: "Verification code",
  confirmCode: "Confirm code",
  confirmingCode: "Confirming",
  emailLabel: "Email address",
  sendEmailLink: "Email me a secure link",
  sendingEmailLink: "Sending link",
  completeEmailSignIn: "Continue with verified email",
  emailSentTitle: "Check your email",
  emailSentBody: "Open the link on this device to continue your saved response.",
  previous: "Back",
  next: "Continue",
  review: "Review answers",
  reviewKicker: "Final check",
  reviewTitle: "Review before submitting",
  reviewBody: "You can go back and change any answer before it is sent.",
  unanswered: "Not answered",
  consentHeading: "Consent and retention",
  submit: "Submit response",
  submitting: "Submitting",
  saveStatus: "Saving draft",
  savedStatus: "Draft saved",
  selectFiles: "Choose files",
  replaceFiles: "Replace files",
  uploadingFile: "Uploading securely",
  uploadedFile: "Upload ready",
  uploadFailed: "Upload failed. Choose the file and try again.",
  removeUpload: "Remove upload",
  signatureInstruction: "Sign inside the box using your finger, pointer, or stylus.",
  typedSignatureLabel: "Or type your full name",
  clearSignature: "Clear signature",
  saveSignature: "Use this signature",
  signatureReady: "Signature ready",
  uploadPending: "Wait for the secure upload to finish before continuing.",
  uploadedAnswer: "Secure upload attached",
  requiredSuffix: "required",
  optionalSuffix: "optional",
  profileFieldDisclosure: "Catch profile field. Saved privately until you claim your profile and choose what to share.",
  organizerCardFieldDisclosure: "Organizer card field. Private to you and this organizer until you choose to share it after claiming your profile.",
  profilePrivacyNote: "Your answers go to this organizer. Marked profile and organizer-card fields are also saved privately in Catch. Other users can see only the fields you choose to share after you claim your profile. Other organizers cannot see this organizer’s card.",
  chooseOne: "Choose one",
  chooseAny: "Choose all that apply",
  confirmAcknowledgement: "I confirm",
  yes: "Yes",
  no: "No",
  completionKicker: "Response received",
  withdraw: "Withdraw response",
  withdrawing: "Withdrawing",
  withdrawnTitle: "Response withdrawn",
  withdrawnBody: "The organizer can no longer treat this response as active.",
  poweredBy: "Powered by",
  privacyNote: "Answers are sent only to the organizer named above.",
  stepLabel: "Form progress",
  genericError: "Something went wrong. Please try again.",
} as const;
