// Mechanically centralized legacy copy. New copy belongs in the page-owned content modules.
export const websiteCopy = {
  "claimmodel_0001": "Catch may ask for a public-page edit, email confirmation, or additional owner-safe source before approval.",
  "claimmodel_0002": "Do not promise automation yet",
  "claimmodel_0003": "Draft the first Catch event",
  "claimmodel_0004": "Find your page",
  "claimmodel_0005": "Founder",
  "claimmodel_0006": "Instagram DM verification still needs backend support, so manual review remains the source of truth.",
  "claimmodel_0007": "Keep proof links stable",
  "claimmodel_0008": "Leave the website, Instagram, event page, or Linktree proof available while Catch reviews ownership.",
  "claimmodel_0009": "Manager",
  "claimmodel_0010": "Marketing",
  "claimmodel_0011": "Official email",
  "claimmodel_0012": "Other",
  "claimmodel_0013": "Owner",
  "claimmodel_0014": "Public proof links",
  "claimmodel_0015": "Get host tools",
  "claimmodel_0016": "Submit official sites, event pages, Instagram bios, Linktree, Luma, or venue pages that connect you to this organizer.",
  "claimmodel_0017": "Use a domain or booking address that appears publicly for the organizer or venue.",
  "claimmodel_0018": "Use the publicly listed business phone so Catch can confirm the claim before owner tools unlock.",
  "claimmodel_0019": "Venue manager",
  "claimmodel_0020": "Venue or business phone",
  "claimmodel_0021": "Verify ownership",
  "claimmodel_0022": "Watch for follow-up",
  "claimmodel_0023": "Your role",
  "claimpage_0024": "Claimable organizer profiles with verified owner review before host tools unlock.",
  "claimpage_0025": "Find listing",
  "claimpage_0026": "For hosts",
  "claimpage_0027": "Host tools",
  "claimpage_0028": "Member site",
  "claimpage_0029": "Organizer search",
  "claimpage_0030": "Start fresh",
  "claimpage_0031": "Trust",
  "claimpagesections_0032": "Already claimed",
  "claimpagesections_0033": "Anything Catch should know before approving ownership",
  "claimpagesections_0034": "Apply as host",
  "claimpagesections_0035": "Approved claims attach this page to a host account before editing, review responses, events, or analytics are unlocked.",
  "claimpagesections_0036": "Avoid duplicate claims",
  "claimpagesections_0037": "Back",
  "claimpagesections_0038": "Business email",
  "claimpagesections_0039": "Business phone",
  "claimpagesections_0040": "Catch does not open a second owner request from this public claim flow. Use the public profile, events, or organizer search instead.",
  "claimpagesections_0041": "Catch has published this source-backed profile, but its owner-review target is not ready. No claim packet can be submitted from this page yet.",
  "claimpagesections_0042": "Catch should only review ownership against a stable generated page or a fresh host packet.",
  "claimpagesections_0043": "Change",
  "claimpagesections_0044": "Check the directory",
  "claimpagesections_0045": "Claim in review",
  "claimpagesections_0046": "Claim packet",
  "claimpagesections_0047": "Claim progress",
  "claimpagesections_0048": "Claim setup in progress",
  "claimpagesections_0049": "Claim your organizer page",
  "claimpagesections_0050": "Contact",
  "claimpagesections_0051": "Contact details and proof links are not collected until the verified claim target is available.",
  "claimpagesections_0052": "Continue",
  "claimpagesections_0053": "Edits, event publishing, review responses, and reports stay attached to the verified owner account.",
  "claimpagesections_0054": "Events",
  "claimpagesections_0055": "Explore host tools",
  "claimpagesections_0056": "If you run events, your club or venue may already be listed. Find your page, verify you own it, and unlock host tools — including the founding host offer.",
  "claimpagesections_0057": "Fix source details, description, photos, and event categories.",
  "claimpagesections_0058": "Hosts can still start fresh",
  "claimpagesections_0059": "How Catch should verify ownership.",
  "claimpagesections_0060": "If the page does not exist yet, the host application can create a cleaner first-party profile.",
  "claimpagesections_0061": "Listing",
  "claimpagesections_0062": "Listing not found",
  "claimpagesections_0063": "Members can still inspect source details, Catch events, reviews, and event outcomes from the profile.",
  "claimpagesections_0064": "My organizer is not listed",
  "claimpagesections_0065": "Need a different organizer?",
  "claimpagesections_0066": "No partial request is created",
  "claimpagesections_0067": "No unclaimed listing found.",
  "claimpagesections_0068": "Note for review",
  "claimpagesections_0069": "Official website, Instagram, Luma, Linktree, or event page",
  "claimpagesections_0070": "Open directory",
  "claimpagesections_0071": "Organizer, venue, category, or city",
  "claimpagesections_0072": "Owner tools stay gated",
  "claimpagesections_0073": "Profile",
  "claimpagesections_0074": "Proof links",
  "claimpagesections_0075": "Public profile remains visible",
  "claimpagesections_0076": "Publish the first Catch event with admission, price, waitlist, and Playbook.",
  "claimpagesections_0077": "Reports",
  "claimpagesections_0078": "Requester",
  "claimpagesections_0079": "Respond as owner and separate public reviews from verified attendee reviews.",
  "claimpagesections_0080": "Reviews",
  "claimpagesections_0081": "Role",
  "claimpagesections_0082": "Search another page",
  "claimpagesections_0083": "Search by organizer name, city, format, or source event before starting a new packet.",
  "claimpagesections_0084": "Search claimable pages",
  "claimpagesections_0085": "Search unclaimed listings",
  "claimpagesections_0086": "Search unclaimed seed pages or start fresh so Catch can review a new host packet.",
  "claimpagesections_0087": "Sign out",
  "claimpagesections_0088": "sources",
  "claimpagesections_0089": "Start as a fresh host so Catch can create the organizer profile from first-party details.",
  "claimpagesections_0090": "Start fresh",
  "claimpagesections_0091": "Start from first-party details",
  "claimpagesections_0092": "Claim your organizer page.",
  "claimpagesections_0093": "The claim URL does not match a generated organizer page. The owner can still apply as a fresh host or search the source-backed directory.",
  "claimpagesections_0094": "The public profile stays visible",
  "claimpagesections_0095": "Track attendance, catches, matches, repeat interest, and safety totals.",
  "claimpagesections_0096": "Unlocks after approval",
  "claimpagesections_0097": "Use the host application if you need to submit first-party organizer details now.",
  "claimpagesections_0098": "Verification method",
  "claimpagesections_0099": "View public listing",
  "claimpagesections_0100": "You can review the organizer facts and public sources while Catch finishes claim setup.",
  "claimpagesections_0101": "Your name",
  "useclaimflowcontroller_0102": "Choose a listing before submitting.",
  "useclaimflowcontroller_0103": "Claim request received. Catch will review ownership before tools unlock.",
  "useclaimflowcontroller_0104": "Claim submission needs the website Firebase/App Check config. The operating packet is ready, but this local build cannot submit it.",
  "useclaimflowcontroller_0105": "Sign in before submitting this claim.",
  "uselistingclaimcontroller_0106": "Claim request received. Catch will review it before ownership changes.",
  "uselistingclaimcontroller_0107": "Sign in before requesting this claim.",
  "homepage_0108": "Curated singles events. Real context. Better conversations.",
  "homepage_0109": "Download",
  "homepage_0110": "Events",
  "homepage_0111": "For hosts",
  "homepage_0112": "Formats",
  "homepage_0113": "Hosts",
  "homepage_0114": "Join waitlist",
  "homepage_0115": "Members",
  "homepage_0116": "Organizers",
  "homepage_0117": "Trust",
  "homepage_0118": "Waitlist",
  "homepagesections_0119": "A dating loop built around showing up.",
  "homepagesections_0120": "Access",
  "homepagesections_0121": "Apply as host",
  "homepagesections_0122": "Be first in your city.",
  "homepagesections_0123": "Browse organizer pages while event projections are added to the public website feed.",
  "homepagesections_0124": "Browse organizers",
  "homepagesections_0125": "Browse the event, show up, catch privately, and let the shared experience carry the first conversation.",
  "homepagesections_0126": "Catch",
  "homepagesections_0127": "Catch event panel",
  "homepagesections_0128": "Catch gives hosts the controls that make singles events safer, more balanced, and more memorable: admission rules, waitlists, cohort shaping, check-in, live facilitation, and aggregate reports.",
  "homepagesections_0129": "Catch host product board",
  "homepagesections_0130": "Catch is format-aware: every event can carry the right amount of structure, from light social flow to guided rotations and reveal moments.",
  "homepagesections_0131": "Check-in, prompts, rotations, and safety controls stay in one surface.",
  "homepagesections_0132": "Create event",
  "homepagesections_0133": "Designed for consent, context, and host control.",
  "homepagesections_0134": "Dinner",
  "homepagesections_0135": "Discover",
  "homepagesections_0136": "Download Catch when your city opens.",
  "homepagesections_0137": "Events with a reason to talk",
  "homepagesections_0138": "Find a hosted run, dinner, game night, or mixer near you. Show up in person, then catch privately with people you actually met.",
  "homepagesections_0139": "Find events",
  "homepagesections_0140": "For hosts who care about the experience, not just the RSVP list.",
  "homepagesections_0141": "Format",
  "homepagesections_0142": "Host",
  "homepagesections_0143": "Host mode",
  "homepagesections_0144": "Host-led prompts",
  "homepagesections_0145": "Join the member waitlist or apply as a founding host. We will reach out as city access opens.",
  "homepagesections_0146": "Live event",
  "homepagesections_0147": "Live module",
  "homepagesections_0148": "Member app",
  "homepagesections_0149": "No public Catch events are projected yet.",
  "homepagesections_0150": "Not another swipe feed. A better way to meet.",
  "homepagesections_0151": "Open directory",
  "homepagesections_0152": "Open organizer directory",
  "homepagesections_0153": "Organizer directory",
  "homepagesections_0154": "Paired rotations, balanced admission, check-in required.",
  "homepagesections_0155": "Pickleball social",
  "homepagesections_0156": "Private catches open only after attendance",
  "homepagesections_0157": "Real events. Real hosts. The match comes after.",
  "homepagesections_0158": "Run events? Your profile can show public sources today, then verified Catch activity after you claim and publish.",
  "homepagesections_0159": "Searchable organizer profiles create a concrete path from discovery to claim, reviews, host tools, events, and app usage.",
  "homepagesections_0160": "See host tools",
  "homepagesections_0161": "See the Catch loop in motion.",
  "homepagesections_0162": "Social run",
  "homepagesections_0163": "Start with what is happening, then choose who to meet.",
  "homepagesections_0164": "Store listings are not public yet. The buttons are in place now so launch traffic can move directly to the app once the listings are approved.",
  "homepagesections_0165": "The public loop starts with real host pages.",
  "homepagesections_0166": "The public website now treats events and organizer pages as one discovery loop: search the city, browse a real host page, then continue into the app when the event opens.",
  "homepagesections_0167": "This week",
  "homepagesections_0168": "Verified reviews",
  "applicationmodel_0169": "Admission",
  "applicationmodel_0170": "Admission and payment policy",
  "applicationmodel_0171": "Attendance and live roster",
  "applicationmodel_0172": "Bar crawl",
  "applicationmodel_0173": "Booking balance preview",
  "applicationmodel_0174": "Capacity, pricing, approval, waitlists, and payment readiness.",
  "applicationmodel_0175": "Catch receives the operating packet, not just an email address.",
  "applicationmodel_0176": "Community meetup",
  "applicationmodel_0177": "Custom format",
  "applicationmodel_0178": "Dinner",
  "applicationmodel_0179": "Event draft",
  "applicationmodel_0180": "Playbook modules you want live at the door, during the room, and after.",
  "applicationmodel_0181": "Playbook setup",
  "applicationmodel_0182": "First event draft",
  "applicationmodel_0183": "Host identity and public link",
  "applicationmodel_0184": "Host introduction help",
  "applicationmodel_0185": "Host profile",
  "applicationmodel_0186": "Independent host",
  "applicationmodel_0187": "Monthly",
  "applicationmodel_0188": "Need Catch payment onboarding",
  "applicationmodel_0189": "Padel or pickleball",
  "applicationmodel_0190": "Post-event report",
  "applicationmodel_0191": "Private catch window",
  "applicationmodel_0192": "Pub quiz",
  "applicationmodel_0193": "Ranked timed offers",
  "applicationmodel_0194": "Request to join",
  "applicationmodel_0195": "Run of show",
  "applicationmodel_0196": "Singles mixer",
  "applicationmodel_0197": "Social run",
  "applicationmodel_0198": "Starter groups",
  "applicationmodel_0199": "Submit",
  "applicationmodel_0200": "The first event you want to publish, with enough detail for a real setup review.",
  "applicationmodel_0201": "Timed partner rotations",
  "applicationmodel_0202": "Verified attendee reviews",
  "applicationmodel_0203": "Welcome script",
  "applicationmodel_0204": "Who you are, what you run, and where Catch should place the operating profile.",
  "hostapplicationflow_0205": "Admission model",
  "hostapplicationflow_0206": "Already sell paid tickets",
  "hostapplicationflow_0207": "Application completeness",
  "hostapplicationflow_0208": "Approval still has to happen before the website can create clubs, events, payouts, or owner dashboards on your behalf.",
  "hostapplicationflow_0209": "Back",
  "hostapplicationflow_0210": "Balanced ratio",
  "hostapplicationflow_0211": "Better gender balance, less awkward arrivals, verified reviews, repeat attendance...",
  "hostapplicationflow_0212": "Biweekly",
  "hostapplicationflow_0213": "Broadcast first come first served",
  "hostapplicationflow_0214": "Browse organizer pages",
  "hostapplicationflow_0215": "Cadence",
  "hostapplicationflow_0216": "Claim an existing listing",
  "hostapplicationflow_0217": "Community",
  "hostapplicationflow_0218": "Community or venue link",
  "hostapplicationflow_0219": "Constraints, safety needs, venue rules, approval preferences, payout timing, or launch questions",
  "hostapplicationflow_0220": "Continue",
  "hostapplicationflow_0221": "Email",
  "hostapplicationflow_0222": "Event company",
  "hostapplicationflow_0223": "Playbook",
  "hostapplicationflow_0224": "Playbook modules to start with",
  "hostapplicationflow_0225": "Expected capacity",
  "hostapplicationflow_0226": "First Catch event",
  "hostapplicationflow_0227": "First event",
  "hostapplicationflow_0228": "Formats you want to run",
  "hostapplicationflow_0229": "Free events first",
  "hostapplicationflow_0230": "Full name",
  "hostapplicationflow_0231": "Host application received",
  "hostapplicationflow_0232": "Host application steps",
  "hostapplicationflow_0233": "Host type",
  "hostapplicationflow_0234": "Independent host",
  "hostapplicationflow_0235": "Instagram, website, Luma, Linktree, or venue page",
  "hostapplicationflow_0236": "Invite-only",
  "hostapplicationflow_0237": "Long table no. 1, Saturday run, singles mixer",
  "hostapplicationflow_0238": "Manual review",
  "hostapplicationflow_0239": "Members-only",
  "hostapplicationflow_0240": "Monthly",
  "hostapplicationflow_0241": "Need Catch payment onboarding",
  "hostapplicationflow_0242": "No waitlist",
  "hostapplicationflow_0243": "One-off launch",
  "hostapplicationflow_0244": "Open booking",
  "hostapplicationflow_0245": "Operating city",
  "hostapplicationflow_0246": "Operating notes",
  "hostapplicationflow_0247": "Operations",
  "hostapplicationflow_0248": "Organizer, venue, or community name",
  "hostapplicationflow_0249": "Payment readiness",
  "hostapplicationflow_0250": "Price range",
  "hostapplicationflow_0251": "Profile",
  "hostapplicationflow_0252": "Quarterly",
  "hostapplicationflow_0253": "Ranked timed offers",
  "hostapplicationflow_0254": "Request to join",
  "hostapplicationflow_0255": "Run club",
  "hostapplicationflow_0256": "Sponsor or venue-funded",
  "hostapplicationflow_0257": "Target date",
  "hostapplicationflow_0258": "This submits a real host lead packet for review. Creating clubs, events, payout accounts, and owner dashboards still requires approval because those backend callables are host-authenticated.",
  "hostapplicationflow_0259": "Venue",
  "hostapplicationflow_0260": "Venue or meeting area",
  "hostapplicationflow_0261": "Waitlist plan",
  "hostapplicationflow_0262": "Weekly",
  "hostapplicationflow_0263": "What should Catch help you improve?",
  "hostapplicationflow_0264": "What this does now",
  "hostapplicationflow_0265": "Your city",
  "usehostapplicationcontroller_0266": "Finish the required profile, event, and operating fields before submitting.",
  "hostpage_0267": "Apply",
  "hostpage_0268": "Apply as host",
  "hostpage_0269": "Fill room",
  "hostpage_0270": "Host-led singles events with booking, facilitation, matching, and insight.",
  "hostpage_0271": "Live mode",
  "hostpage_0272": "Member site",
  "hostpage_0273": "Organizers",
  "hostpage_0274": "Screens",
  "hostpage_0275": "Workflow",
  "createeventwalkthrough_0276": "An event goes live in five steps",
  "createeventwalkthrough_0277": "Create event · step",
  "createeventwalkthrough_0278": "Create event steps",
  "createeventwalkthrough_0279": "From the host app · Create flow",
  "createeventwalkthrough_0280": "Save draft",
  "createeventwalkthrough_0281": "This is the actual flow, not a brochure: details, location, schedule, then the two steps no ticketing tool has — a full admission policy and a live run-of-show guide.",
  "hostcomparisonsection_0282": "Admission rules, waitlists, check-in, live console, attendance proof, post-event matching, verified reviews, and host reports stay in one loop.",
  "hostcomparisonsection_0283": "Announcing an event is solved. Running one is not.",
  "hostcomparisonsection_0284": "Capability",
  "hostcomparisonsection_0285": "Catch",
  "hostcomparisonsection_0286": "Catch fills it, runs it, and proves it.",
  "hostcomparisonsection_0287": "District and BookMyShow are strong Indian discovery and ticketing surfaces. Catch is positioned around the host operating loop after the listing goes live.",
  "hostcomparisonsection_0288": "Full table",
  "hostcomparisonsection_0289": "Luma · Eventbrite · District · BookMyShow · Instagram · WhatsApp · Forms",
  "hostcomparisonsection_0290": "The honest comparison",
  "hostcomparisonsection_0291": "They help you publish, sell, or get discovered.",
  "hostcomparisonsection_0292": "Useful reach, event pages, and payments. Then social hosts still assemble admissions, ratios, door proof, follow-up, and reputation signals across scattered tools.",
  "hostpagesections_0293": "Admission",
  "hostpagesections_0294": "After event",
  "hostpagesections_0295": "Apply as a founding host if you run events, communities, venues, or formats where the right singles can meet with more context.",
  "hostpagesections_0296": "Apply as host",
  "hostpagesections_0297": "Bring the format. Catch handles the loop around it.",
  "hostpagesections_0298": "Catch answers more than \"who RSVP'd?\" It shows where demand came from, where people dropped off, and whether the event created real connection afterward.",
  "hostpagesections_0299": "Catch gives hosts the controls to shape demand, guide the live experience, and understand what happened after people met.",
  "hostpagesections_0300": "Catch handles the loop around your event: booking logic, admission, waitlists, live facilitation, check-in, private catches, and the post-event report that shows what actually happened.",
  "hostpagesections_0301": "Catch shows the path from interest to attendance to follow-up.",
  "hostpagesections_0302": "Checkout, waitlist, and cohort controls belong in the same roster.",
  "hostpagesections_0303": "Playbook",
  "hostpagesections_0304": "Fill the room",
  "hostpagesections_0305": "Host confidence",
  "hostpagesections_0306": "Host console",
  "hostpagesections_0307": "Host tools",
  "hostpagesections_0308": "Live",
  "hostpagesections_0309": "Live facilitation is built into the event flow.",
  "hostpagesections_0310": "Live moment",
  "hostpagesections_0311": "One loop, from booking to connection.",
  "hostpagesections_0312": "Replace forms, payment links, spreadsheets, group chats, manual intros, and safety notes with one flow built around the event.",
  "hostpagesections_0313": "Report",
  "hostpagesections_0314": "Run singles events people actually follow through on.",
  "hostpagesections_0315": "Run the whole event loop from one place.",
  "hostpagesections_0316": "See the host workflow end to end.",
  "hostpagesections_0317": "See workflow",
  "hostpagesections_0318": "Set up the event, manage the live moment, and review the signals that help the next event get better.",
  "hostpagesections_0319": "Setup",
  "hostpagesections_0320": "The live catalog is explicit: booking balance preview, attendance and roster, welcome scripts, prompts, assignments, rotations, private catches, feedback, and aggregate host reports.",
  "hostpagesections_0321": "The mockup split these into concrete host promises. In production they should stay connected to the event record instead of becoming separate ticketing, spreadsheet, or DM workflows.",
  "hostpagesections_0322": "The platform is not just ticketing, and it is not just matching.",
  "hostpagesections_0323": "What a host can see",
  "hostpagesections_0324": "What Catch handles",
  "playbookshowcase_0325": "Playbook module catalog",
  "playbookshowcase_0326": "The guest experience",
  "marketingconsentbanner_0327": "Accept all",
  "marketingconsentbanner_0328": "Analytics consent",
  "marketingconsentbanner_0329": "Catch uses analytics and ad measurement to understand which campaigns bring real waitlist and host demand.",
  "marketingconsentbanner_0330": "Essential only",
  "notfoundpage_0331": "Browse the member site",
  "notfoundpage_0332": "Claim a listing",
  "notfoundpage_0333": "Curated singles events. Real context. Better conversations.",
  "notfoundpage_0334": "Host on Catch",
  "notfoundpage_0335": "If you own the page you expected, start from the host route or claim search.",
  "notfoundpage_0336": "Look up public profiles by city, format, organizer name, or review signal.",
  "notfoundpage_0337": "Browse events",
  "notfoundpage_0338": "Open host tools",
  "notfoundpage_0339": "Organizers",
  "notfoundpage_0340": "Page not found",
  "notfoundpage_0341": "Return to the public homepage for the current Catch event flow.",
  "notfoundpage_0342": "Organizer directory",
  "notfoundpage_0343": "Search the organizer directory",
  "notfoundpage_0344": "The link may be old, or the page may have moved.",
  "notfoundpage_0345": "This page never checked in.",
  "hostlistingpage_0346": "Claimable profiles for hosts who run social events people actually show up for.",
  "organizersearchpage_0347": "Apply as host",
  "organizersearchpage_0348": "Dinners",
  "organizersearchpage_0349": "For hosts",
  "organizersearchpage_0350": "Member site",
  "organizersearchpage_0351": "Run clubs",
  "organizersearchpage_0352": "Searchable profiles for hosts, clubs, venues, and social organizers.",
  "publicdiscovery_0353": "booked",
  "publicdiscovery_0354": "Capacity",
  "publicdiscovery_0355": "checked in",
  "publicdiscovery_0356": "Claim or correct this listing",
  "publicdiscovery_0357": "Date",
  "publicdiscovery_0358": "Location",
  "publicdiscovery_0359": "Open source page",
  "publicdiscovery_0360": "Price",
  "publicdiscovery_0361": "See outcomes",
  "publicdiscovery_0362": "Source",
  "publicdiscovery_0363": "waitlisted",
  "listingclaimsections_0364": "Anything Catch should know before approving ownership",
  "listingclaimsections_0365": "Apply as host",
  "listingclaimsections_0366": "This profile was assembled from public sources. Claim it to correct the facts, reply to reviews, add photos — and publish bookable events with Catch host tools.",
  "listingclaimsections_0367": "Before public indexing",
  "listingclaimsections_0368": "Business email",
  "listingclaimsections_0369": "Business phone",
  "listingclaimsections_0370": "cannot show yet.",
  "listingclaimsections_0371": "Claim this page",
  "listingclaimsections_0372": "Claiming unlocks",
  "listingclaimsections_0373": "Missing evidence",
  "listingclaimsections_0374": "Note for review",
  "listingclaimsections_0375": "Official website, Instagram, Luma, Linktree, or event page",
  "listingclaimsections_0376": "Owner review is not enabled for this listing.",
  "listingclaimsections_0377": "Proof links",
  "listingclaimsections_0378": "Is this your page? ",
  "listingclaimsections_0379": "Role",
  "listingclaimsections_0380": "Sign out",
  "listingclaimsections_0381": "This is the pressure mechanic from the prototype: visitors can see what is known, what is missing, and why a verified Catch profile earns stronger placement.",
  "listingclaimsections_0382": "Use the host application while this public claim flow is being connected.",
  "listingclaimsections_0383": "What",
  "listingclaimsections_0384": "Your name",
  "listingeventssections_0385": "Booked, checked in, and reviewed in the app. This is the organizer’s verified track record.",
  "listingeventssections_0386": "Book, check in, and review from Catch.",
  "listingeventssections_0387": "Booked",
  "listingeventssections_0388": "Catch events",
  "listingeventssections_0389": "Catches sent",
  "listingeventssections_0390": "Chats started",
  "listingeventssections_0391": "Checked in",
  "listingeventssections_0392": "Event evidence",
  "listingeventssections_0393": "Playbook",
  "listingeventssections_0394": "Events run on Catch",
  "listingeventssections_0395": "External events",
  "listingeventssections_0396": "Member app",
  "listingeventssections_0397": "Mutual matches",
  "listingeventssections_0398": "Public events tied to this host.",
  "listingeventssections_0399": "Public pages expose the event record. The app handles booking, waitlist movement, attendance, catches, and verified reviews.",
  "listingeventssections_0400": "Safety reports",
  "listingeventssections_0401": "Events from public sources",
  "listingeventssections_0402": "The claimed profile can show what Catch actually operated.",
  "listingeventssections_0403": "These are aggregate, host-safe outcomes from a completed Catch event. This is the kind of proof an app-created club can show that a scraped unclaimed listing cannot.",
  "listingeventssections_0404": "Listed for reference from public pages. Catch does not handle booking or attendance for these, so they do not count toward verified history.",
  "listingherosection_0405": "Aggregate host report available",
  "listingherosection_0406": "Catch events attached to profile",
  "listingherosection_0407": "Listing status",
  "listingherosection_0408": "members",
  "listingherosection_0409": "No Catch events published",
  "listingherosection_0410": "No verified attendee reviews",
  "listingherosection_0411": "Organizer metrics",
  "listingherosection_0412": "Ownership and source model verified",
  "listingherosection_0413": "Ownership not verified",
  "listingherosection_0414": "Public facts collected from sources",
  "listingherosection_0415": "rating",
  "listingherosection_0416": "Review signal visible",
  "listingherosection_0417": "reviews",
  "listingherosection_0418": "Share listing",
  "listingreviewssection_0419": "1 star",
  "listingreviewssection_0420": "2 stars",
  "listingreviewssection_0421": "3 stars",
  "listingreviewssection_0422": "4 stars",
  "listingreviewssection_0423": "5 stars",
  "listingreviewssection_0424": "Add review",
  "listingreviewssection_0425": "Add the first public review here. If the organizer claims this page, they can respond from the verified host account.",
  "listingreviewssection_0426": "Count",
  "listingreviewssection_0427": "Display name",
  "listingreviewssection_0428": "First review",
  "listingreviewssection_0429": "No public reviews for",
  "listingreviewssection_0430": "No public web reviews yet.",
  "listingreviewssection_0431": "No verified attendee reviews are visible yet.",
  "listingreviewssection_0432": "Post anonymously",
  "listingreviewssection_0433": "Public reviews can be added here; Catch keeps them clearly labeled until they can be tied to a verified event.",
  "listingreviewssection_0434": "Public reviews for",
  "listingreviewssection_0435": "Rating",
  "listingreviewssection_0436": "Review",
  "listingreviewssection_0437": "Reviews",
  "listingreviewssection_0438": "Share feedback for",
  "listingreviewssection_0439": "Submitted on this page. Useful, but not proof of attendance.",
  "listingreviewssection_0440": "From guests who checked in at this organizer’s Catch events.",
  "listingreviewssection_0441": "Public reviews",
  "listingreviewssection_0442": "Verified",
  "listingreviewssection_0443": "Verified attendee reviews appear after Catch has operated the event and confirmed attendance.",
  "listingreviewssection_0444": "Verified guest reviews",
  "listingreviewssection_0445": "Verified reviews come from logged-in Catch guests after attended events. Reviews submitted on this public page are unverified and can be anonymous.",
  "listingreviewssection_0446": "What should people know about this organizer?",
  "listingreviewssection_0447": "yet.",
  "listingsourcessection_0448": "Evidence before indexing.",
  "listingsourcessection_0449": "Source ledger",
  "listingsourcessection_0450": "Thin pages should stay out of search until identity, cadence, and owner-safe details are verified.",
  "organizersearchsections_0451": "Any city",
  "organizersearchsections_0452": "Any format",
  "organizersearchsections_0453": "Any rating",
  "organizersearchsections_0454": "Any status",
  "organizersearchsections_0455": "City",
  "organizersearchsections_0456": "Claim pressure",
  "organizersearchsections_0457": "claimable pages",
  "organizersearchsections_0458": "claimable seed pages",
  "organizersearchsections_0459": "Claimed",
  "organizersearchsections_0460": "Clear filters",
  "organizersearchsections_0461": "event-backed pages",
  "organizersearchsections_0462": "Every club, venue, and host running real events.",
  "organizersearchsections_0463": "Format",
  "organizersearchsections_0464": "Has upcoming events",
  "organizersearchsections_0465": "Most reviewed",
  "organizersearchsections_0466": "No organizer profiles match those filters.",
  "organizersearchsections_0467": "Open claim flow",
  "organizersearchsections_0468": "Organizer results",
  "organizersearchsections_0469": "Organizer search",
  "organizersearchsections_0470": "profiles tracked",
  "organizersearchsections_0471": "proof gaps",
  "organizersearchsections_0472": "Public pages work harder when the owner steps in.",
  "organizersearchsections_0473": "Rating",
  "organizersearchsections_0474": "Relevance",
  "organizersearchsections_0475": "Reset directory",
  "organizersearchsections_0476": "Search",
  "organizersearchsections_0477": "Search clubs, venues, hosts…",
  "organizersearchsections_0478": "Search by name, city, or format. See verified guest reviews, upcoming events, and which organizers are live on Catch.",
  "organizersearchsections_0479": "Seed pages expose source evidence and proof gaps. Claimed pages can add official details, publish Catch events, separate verified attendee reviews, and respond as the host.",
  "organizersearchsections_0480": "Sort",
  "organizersearchsections_0481": "Source confidence",
  "organizersearchsections_0482": "Status",
  "organizersearchsections_0483": "Try a wider city, format, or status filter.",
  "organizersearchsections_0484": "Search clubs, venues, hosts…",
  "organizersearchsections_0485": "Unclaimed",
  "organizersearchsections_0486": "Upcoming first",
  "organizersearchsections_0487": "verified on Catch",
  "organizersearchsections_0488": "Verified on Catch",
  "recommendedorganizerssection_0489": "Unclaimed pages keep the source ledger visible, but verified profiles can show owner-managed activity, reviews, and event outcomes.",
  "recommendedorganizerssection_0490": "Verified organizers nearby in the product loop.",
  "recommendedorganizerssection_0491": "While you are here",
  "usehostlistingpagecontroller_0492": "Claim",
  "usehostlistingpagecontroller_0493": "Events",
  "usehostlistingpagecontroller_0494": "For hosts",
  "usehostlistingpagecontroller_0495": "Profile",
  "usehostlistingpagecontroller_0496": "Reviews",
  "usehostlistingpagecontroller_0497": "Search",
  "usehostlistingpagecontroller_0498": "Sources",
  "reviewmodel_0499": "public reviews",
  "reviewmodel_0500": "published responses",
  "reviewmodel_0501": "verified signals",
  "uselistingreviewscontroller_0502": "Add your name, or choose anonymous.",
  "uselistingreviewscontroller_0503": "Preview review added locally. Configure website App Check to write it to Firestore.",
  "uselistingreviewscontroller_0504": "Review published as an unverified public review.",
  "uselistingreviewscontroller_0505": "Review text is required.",
  "usewaitlistformcontroller_0506": "Both",
  "usewaitlistformcontroller_0507": "Choose role",
  "usewaitlistformcontroller_0508": "Host",
  "usewaitlistformcontroller_0509": "Host and member",
  "usewaitlistformcontroller_0510": "Member",
  "usewaitlistformcontroller_0511": "Please fill out your name, email, city, and role.",
  "waitlistform_0512": "Choose city",
  "waitlistform_0513": "City",
  "waitlistform_0514": "Email",
  "waitlistform_0515": "Full name",
  "waitlistform_0516": "Joining as",
  "waitlistform_0517": "Your city",
  "sitefooter_0518": "C",
  "sitefooter_0519": "Catch",
  "sitefooter_0520": "Catch home",
  "sitefooter_0521": "Footer",
  "siteheader_0522": "C",
  "siteheader_0523": "Catch",
  "siteheader_0524": "Catch home",
  "siteheader_0525": "Primary",
  "primitives_0526": "confidence",
  "primitives_0527": "external",
  "primitives_0528": "Fits:",
  "primitives_0529": "For attendees:",
  "primitives_0530": "For hosts:",
  "primitives_0531": "Host response ·",
  "primitives_0532": "listing-hero__eyebrow",
  "primitives_0533": "Location",
  "primitives_0534": "Owner response",
  "primitives_0535": "proof-section",
  "primitives_0536": "proof-section__copy",
  "primitives_0537": "Search Catch",
  "primitives_0538": "Source",
  "primitives_0539": "visible",
  "primitives_0540": "waitlisted"
} as const;
