/** Deterministic browser/test fixture; never selects a live program or token. */
export const householdRsvpViewFixture = {
  programId: "fixture-program",
  programTitle: "Asha & Rohan's Wedding",
  timezone: "Asia/Kolkata",
  householdId: "fixture-household",
  householdLabel: "Sharma family",
  messagingConsentGranted: false,
  members: [
    {
      guestId: "fixture-guest-1",
      displayName: "Ashok Sharma",
      functions: [
        {
          functionId: "fixture-sangeet",
          name: "Sangeet",
          startsAtMillis: 1_800_600_000_000,
          endsAtMillis: 1_800_603_000_000,
          venueName: "The Courtyard",
          dressCode: "Festive",
          instructions: null,
          rsvpStatus: "pending" as const,
          partySize: null,
          responseNote: null,
        },
        {
          functionId: "fixture-reception",
          name: "Reception",
          startsAtMillis: 1_800_700_000_000,
          endsAtMillis: 1_800_703_000_000,
          venueName: "Grand Hall",
          dressCode: "Formal",
          instructions: "Doors open at 6:30 pm.",
          rsvpStatus: "attending" as const,
          partySize: 2,
          responseNote: null,
        },
      ],
      travel: [
        {
          kind: "inbound" as const,
          flightNumber: "AI 610",
          carrierCode: "AI",
          originIata: "BOM",
          destinationIata: "JAI",
          scheduledArrivalAtMillis: 1_800_500_000_000,
          destinationHotelId: "fixture-hotel-1",
          destinationLabel: null,
          passengers: 2,
          luggageUnits: 3,
        },
      ],
    },
    {
      guestId: "fixture-guest-2",
      displayName: "Meena Sharma",
      functions: [
        {
          functionId: "fixture-sangeet",
          name: "Sangeet",
          startsAtMillis: 1_800_600_000_000,
          endsAtMillis: 1_800_603_000_000,
          venueName: "The Courtyard",
          dressCode: "Festive",
          instructions: null,
          rsvpStatus: "pending" as const,
          partySize: null,
          responseNote: null,
        },
      ],
      travel: [],
    },
  ],
  hotels: [
    {hotelId: "fixture-hotel-1", name: "Grand Palace"},
    {hotelId: "fixture-hotel-2", name: "Lakeview Residency"},
  ],
};

export const householdRsvpCopy = {
  brand: "Catch home", brandWord: "catch", kicker: "You're invited",
  loadingTitle: "Getting your invitation",
  loading: "Loading your household's invitation…",
  unavailableTitle: "This invitation link is unavailable",
  unavailableBody: "Open the latest link from your message. It may have expired or been replaced.",
  networkTitle: "We couldn't load your invitation",
  networkBody: "Check your connection and try again.",
  refresh: "Refresh", refreshing: "Refreshing…",
  attending: "Attending", maybe: "Maybe", declined: "Can't make it",
  partySize: "Seats needed", partySizePlaceholder: "1",
  note: "Anything we should know? (optional)",
  notePlaceholder: "Allergies, accessibility, travel timing…",
  consentLabel:
    "It's OK to message this household about schedule changes and event updates.",
  submit: "Send RSVP", sending: "Sending your RSVP…",
  saved: "Your RSVP is saved. You can update it any time before the event.",
  uncertain:
    "We couldn't confirm your RSVP. Check your connection and try again.",
  itinerary: "Add to calendar (.ics)",
  dressCodeLabel: "Dress code:",
  functionsHeading: "Functions",
  membersHeading: "Your household",
  travelHeading: "Travel (optional)",
  travelBlockTitle: (name: string, kindLabel: string) =>
    `${name} · ${kindLabel}`,
  travelArrival: "Arrival",
  travelDeparture: "Departure",
  travelFlight: "Flight or train number",
  travelFlightPlaceholder: "e.g. AI 610 or 12951",
  travelFrom: "From (airport/station code)",
  travelFromPlaceholder: "e.g. BOM",
  travelTo: "To (airport/station code)",
  travelToPlaceholder: "e.g. JAI",
  travelWhen: "Lands at",
  travelWhenDeparture: "Departs at",
  travelHotel: "Staying at",
  travelHotelOther: "Somewhere else",
  travelHotelChoose: "Choose a hotel",
  travelDestinationLabel: "Where exactly? (optional)",
  travelDestinationPlaceholder: "Hotel name or address",
  travelPassengers: "Travellers",
  travelLuggage: "Bags",
  travelIncomplete:
    "Add a landing time and a hotel or destination so we can plan pickups.",
};
