/** Copy for the private, synthetic host workflow preview. */
export const salesDemoCopy = {
  privateExample: "Private example",
  privateWorkflowPreview: "Private workflow preview",
  "phonePlaceholder": "+91…",
  "catch": "Catch",
  "thisPreviewIsUnavailable": "This preview is unavailable",
  "theInvitationMayHaveExpiredOr": "The invitation may have expired or changed. Ask the inviter for a current link.",
  "tryAgain": "Try again",
  "loadingPrivatePreview": "Loading private preview…",
  "whatYouCanExplore": "What you can explore",
  "whatStaysWithYourCurrentTools": "What stays with your current tools",
  "knownLimitsOfThisExample": "Known limits of this example",
  "availableUntil": "Available until",
  "noRealMessagesChargesGuestAdmission": "No real messages, charges, guest admission, organizer ownership, or publication occur here.",
  "googleSigninDidNotCompleteYou": "Google sign-in did not complete. You can try again.",
  "phoneVerificationCouldNotStartCheck": "Phone verification could not start. Check the number and try again.",
  "thatVerificationCodeCouldNotBe": "That verification code could not be confirmed. Try again.",
  "previewOnly": "Preview only",
  "interactiveAccessHasNotBeenEnabled": "Interactive access has not been enabled for this invitation. Ask the inviter to review the intended contact if you want to try the sample workflow.",
  "interactiveLinkNeeded": "Interactive link needed",
  "thisPreviewIsSafeToView": "This preview is safe to view, but its interactive grant is missing. Open the original invitation link or ask the inviter for a new one.",
  "tryTheSampleWorkflow": "Try the sample workflow",
  "checkingSignin": "Checking sign-in…",
  "signedInAs": "Signed in as",
  "theServerWillCheckThisIdentity": ". The server will check this identity against the invitation.",
  "openingSample": "Opening sample…",
  "openInteractiveExample": "Open interactive example",
  "useTheInvitedEmailOrVerify": "Use the invited email or verify the invited phone. If you are signed in with another account, you can change it below.",
  "orVerifyPhoneInternationalFormat": "Or verify phone (international format)",
  "sendVerificationCode": "Send verification code",
  "verificationCode": "Verification code",
  "verifyPhone": "Verify phone",
  "changeNumberOrResendCode": "Change number or resend code",
  "yourIsolatedSample": "Your isolated sample",
  "step": "Step:",
  "sampleApplicant": "Sample applicant:",
  "review": "Review:",
  "reply": "· Reply:",
  "guest": "· Guest:",
  "onlySyntheticRecordsAreChanged": "Only synthetic records are changed.",
  "nextSampleStep": "Next sample step",
  "checkTheLatestSessionBeforeContinuing": "Check the latest session before continuing.",
  "retry": "Retry:",
  "requestHelpWithThisDemo": "Request help with this demo",
  "refreshSampleStatus": "Refresh sample status",
  "assistanceRequestedThisRecordsAnInproduct": "Assistance requested. This records an in-product request; no message is sent here.",
  "youCompletedThisSyntheticWorkflowA": "You completed this synthetic workflow. A real product setup requires a separate reviewed host handoff.",
  "approveSampleApplication": "Approve sample application",
  "askSampleApplicantForMoreInformation": "Ask sample applicant for more information",
  "prepareClarificationExample": "Prepare clarification example",
  "prepareWelcomeExample": "Prepare welcome example",
  "admitSampleGuest": "Admit sample guest",
  "noFurtherSampleStepIsAvailable": "No further sample step is available."
} as const;
