/** Copy for the account-bound continuation of a reviewed private sample. */
export const continuationCopy = {
  kicker: "Private Host setup",
  title: "Continue your organizer onboarding",
  body: "Your practice example remains synthetic. Claim review, preparing a real draft and publishing an event require separate actions.",
  checkingAccount: "Checking your account",
  checkingSetup: "Checking current private setup",
  sameAccount: "Keep the same account in Host",
  requestControl: "Request organizer control",
  invitedPhone: "Verify invited phone (international format)",
  verificationCode: "Verification code",
  yourName: "Your name",
  yourRole: "Your role",
  businessEmail: "Business email",
  businessPhone: "Business phone",
  proofLinks: "Public proof links",
  ownershipContext: "Ownership context for review",
  footer: "Claim review and real event publication remain separate.",
  invalidLink: "This private setup link is invalid.",
  signInPrompt: "Sign in with the account that completed the sample.",
  accessChanged: "This setup has expired or current access changed. Use the original account or ask the inviter to review access.",
  checkAccess: "Check access again",
  linkPhone: "Link the phone you will use in Catch before continuing. Complete your Catch profile on that phone account; approval requires a completed profile on this same account.",
  openCatch: "Open Catch to complete your profile",
  claimPending: "Organizer ownership is already under review. Check status after the review; no new request is needed.",
  hasOwner: "This organizer has an owner. Ask that owner for the appropriate team invitation before preparing a draft.",
  manualReview: "This setup needs the Catch team's review.",
  prepareGuidance: "Prepare a private draft from the reviewed template. Review its questions and consent in Host before publishing.",
  prepareDraft: "Prepare reviewed private draft",
  prepared: "Your private draft is prepared. It has not been published.",
  finishForms: "Finish in Host Forms",
  openForms: "Open Host Forms in the Catch app to continue.",
  checkStatus: "Check claim and setup status",
  ownershipGuidance: "The completed demo does not prove ownership. This is a request for organizer ownership, subject to review. Add your ownership authority and evidence. It does not publish your organizer. Non-owner collaborators should ask the organizer owner for a team invitation.",
  submitClaim: "Submit claim for review",
  restartPhone: "Restart phone verification",
  signOut: "Sign out to recover a different account",
  verifyGoogle: "Verify Google for this account",
  continueGoogle: "Continue with Google",
  verifyPhone: "Verify phone",
  sendCode: "Send verification code",
  restartContact: "Restart contact verification.",
  retryRequest: "Check status before retrying this request.",
  refreshBeforeRetry: "Refresh the setup before retrying.",
  availableUntil: (date: string) => `Available until ${date}.`,
  awaitingReview: (requestId: string) => `Claim request ${requestId} is awaiting review. Check status above after review.`,
} as const;
