// Hand-written domain class (NOT generated by generate_domain_classes.mjs).
// PaymentStatus owns per-member docs + an unknownEnumValue decode fail-safe the
// generator does not synthesize; see HAND_WRITTEN_NOTES in that generator.
import 'package:catch_dating_app/core/country_markets.dart';
import 'package:catch_dating_app/core/firestore_converters.dart';
import 'package:catch_dating_app/core/labelled.dart';
import 'package:freezed_annotation/freezed_annotation.dart';

part 'payment.freezed.dart';
part 'payment.g.dart';

enum PaymentStatus implements Labelled {
  pending('Pending'),
  completed('Completed'),
  failed('Failed'),
  refunded('Refunded'),

  /// The booking failed AND the automatic refund could not be issued, so the
  /// charge is stuck and needs manual reconciliation. Distinct from [refunded]
  /// (money returned) so support and the user can tell them apart.
  refundFailed('Refund failed');

  const PaymentStatus(this.label);
  @override
  final String label;
}

@freezed
abstract class Payment with _$Payment {
  const factory Payment({
    @JsonKey(includeToJson: false) required String id,
    required String userId,
    required String orderId,
    required String paymentId,
    required String eventId,
    required int amount,
    @Default(defaultCurrencyCode) String currency,
    @JsonKey(unknownEnumValue: PaymentStatus.failed)
    required PaymentStatus status,
    @Default(false) bool signUpFailed,
    @TimestampConverter() required DateTime createdAt,
  }) = _Payment;

  factory Payment.fromJson(Map<String, dynamic> json) =>
      _$PaymentFromJson(json);
}
