// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZUkQpo1xw1GYOLhdRh5RbVdy0wq8A644',
    appId: '1:574779808785:web:0c3bd6aa7d98590f8ea5b0',
    messagingSenderId: '574779808785',
    projectId: 'catch-dating-app-64e51',
    authDomain: 'catch-dating-app-64e51.firebaseapp.com',
    storageBucket: 'catch-dating-app-64e51.firebasestorage.app',
    measurementId: 'G-CH7WMQY5FV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6dvdBlfV8nU5RJvcQa6QTp8Ej25QhBV8',
    appId: '1:574779808785:android:8d7b61e9d54592f68ea5b0',
    messagingSenderId: '574779808785',
    projectId: 'catch-dating-app-64e51',
    storageBucket: 'catch-dating-app-64e51.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtL_D8Cf3OMBeL1ffnmKse4VI2i_WUq7E',
    appId: '1:574779808785:ios:ee42e89efaf280f78ea5b0',
    messagingSenderId: '574779808785',
    projectId: 'catch-dating-app-64e51',
    storageBucket: 'catch-dating-app-64e51.firebasestorage.app',
    iosBundleId: 'com.example.catchDatingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCtL_D8Cf3OMBeL1ffnmKse4VI2i_WUq7E',
    appId: '1:574779808785:ios:ee42e89efaf280f78ea5b0',
    messagingSenderId: '574779808785',
    projectId: 'catch-dating-app-64e51',
    storageBucket: 'catch-dating-app-64e51.firebasestorage.app',
    iosBundleId: 'com.example.catchDatingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZUkQpo1xw1GYOLhdRh5RbVdy0wq8A644',
    appId: '1:574779808785:web:defa51d04129bf1d8ea5b0',
    messagingSenderId: '574779808785',
    projectId: 'catch-dating-app-64e51',
    authDomain: 'catch-dating-app-64e51.firebaseapp.com',
    storageBucket: 'catch-dating-app-64e51.firebasestorage.app',
    measurementId: 'G-9K5PP9HE4X',
  );
}
