import 'dart:convert';
import 'dart:io';

const _tokenPath = 'design/tokens/catch.tokens.json';
const _defaultWebsiteCssPath = 'packages/web-config/generated/catch-tokens.css';
const _defaultDartTokensPath =
    'lib/core/theme/generated/catch_design_tokens.g.dart';

void main(List<String> args) {
  if (args.contains('--help') || args.contains('-h')) {
    _printHelp();
    return;
  }

  final check = args.contains('--check');
  final tokenFile = File(_tokenPath);
  if (!tokenFile.existsSync()) {
    stderr.writeln('Missing token file: $_tokenPath');
    exitCode = 1;
    return;
  }

  final document = jsonDecode(tokenFile.readAsStringSync());
  if (document is! Map<String, dynamic>) {
    stderr.writeln('Token file root must be a JSON object.');
    exitCode = 1;
    return;
  }

  final tokens = _TokenRegistry.fromDocument(document);
  final catchExtension = _catchExtension(document);
  final websiteExtension = _mapValue(catchExtension['website'], 'website');
  final dartExtension = _mapValue(catchExtension['dart'], 'dart');
  final websiteOutputPath =
      websiteExtension['output'] as String? ?? _defaultWebsiteCssPath;
  final dartOutputPath =
      dartExtension['output'] as String? ?? _defaultDartTokensPath;
  final css = _buildWebsiteCss(
    registry: tokens,
    websiteExtension: websiteExtension,
  );
  final dart = _buildDartTokens(tokens);

  final failures = <String>[];
  final websiteOutputFile = File(websiteOutputPath);
  final dartOutputFile = File(dartOutputPath);

  if (check) {
    if (!websiteOutputFile.existsSync()) {
      failures.add('missing $websiteOutputPath');
    } else if (websiteOutputFile.readAsStringSync() != css) {
      failures.add('stale $websiteOutputPath');
    }
    if (!dartOutputFile.existsSync()) {
      failures.add('missing $dartOutputPath');
    } else if (dartOutputFile.readAsStringSync() != dart) {
      failures.add('stale $dartOutputPath');
    }
    failures.addAll(_fontAssetFailures(websiteExtension));

    if (failures.isNotEmpty) {
      stderr.writeln('Design token check failed:');
      for (final failure in failures) {
        stderr.writeln('- $failure');
      }
      stderr.writeln('Run: dart run tool/design_tokens.dart');
      exitCode = 1;
      return;
    }

    stdout.writeln('Design token check passed.');
    return;
  }

  _writeFile(websiteOutputFile, css);
  _writeFile(dartOutputFile, dart);
  _syncFontAssets(websiteExtension);
  stdout.writeln(
    'Generated $websiteOutputPath and $dartOutputPath from $_tokenPath.',
  );
}

String _buildWebsiteCss({
  required _TokenRegistry registry,
  required Map<String, dynamic> websiteExtension,
}) {
  final buffer = StringBuffer()
    ..writeln('/*')
    ..writeln(' * Generated by `dart run tool/design_tokens.dart`.')
    ..writeln(' * Source: $_tokenPath')
    ..writeln(' * Do not edit by hand.')
    ..writeln(' */')
    ..writeln();

  for (final fontFace in _fontFaces(websiteExtension)) {
    buffer
      ..writeln('@font-face {')
      ..writeln('  font-family: "${fontFace.family}";')
      ..writeln('  src: url("${fontFace.url}") format("${fontFace.format}");')
      ..writeln('  font-weight: ${fontFace.weight};')
      ..writeln('  font-style: ${fontFace.style};')
      ..writeln('  font-display: swap;')
      ..writeln('}')
      ..writeln();
  }

  buffer.writeln(':root {');

  for (final token in registry.tokens.values) {
    final cssName = _cssVariableName(token.path);
    final cssValue = registry.cssValue(token);
    if (cssValue == null) continue;
    buffer.writeln('  $cssName: $cssValue;');
  }

  final aliases = _mapValue(websiteExtension['legacyAliases'], 'legacyAliases');
  if (aliases.isNotEmpty) {
    buffer.writeln();
    buffer.writeln(
      '  /* Temporary compatibility aliases for website/styles.css. */',
    );
    for (final entry in aliases.entries) {
      final name = entry.key;
      final value = entry.value;
      final cssValue = registry.cssValueFromExtensionValue(value);
      buffer.writeln('  --$name: $cssValue;');
    }
  }

  buffer
    ..writeln('}')
    ..writeln();

  return buffer.toString();
}

String _buildDartTokens(_TokenRegistry registry) {
  final buffer = StringBuffer()
    ..writeln('// Generated by `dart run tool/design_tokens.dart`.')
    ..writeln('// Source: $_tokenPath')
    ..writeln('// Do not edit by hand.')
    ..writeln()
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('abstract final class GeneratedCatchColorTokens {');

  for (final token in registry.tokens.values.where(_isThemeColorToken)) {
    buffer.writeln(
      '  static const Color ${_dartThemeTokenName(token)} = '
      '${_dartColorValue(registry.resolvedValue(token))};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class GeneratedCatchGradientTokens {');

  for (final token in registry.tokens.values.where(_isThemeGradientToken)) {
    buffer.writeln(
      '  static const Gradient ${_dartThemeTokenName(token)} = '
      '${_dartGradientValue(registry, token)};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class GeneratedCatchSpacingTokens {');

  for (final token in registry.tokens.values.where(_isSpacingToken)) {
    buffer.writeln(
      '  static const double ${token.path.last} = '
      '${_dartDimensionNumber(registry.resolvedValue(token))};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class GeneratedCatchRadiusTokens {');

  for (final token in registry.tokens.values.where(_isRadiusToken)) {
    buffer.writeln(
      '  static const double ${token.path.last} = '
      '${_dartDimensionNumber(registry.resolvedValue(token))};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class GeneratedCatchFontFamilyTokens {');

  for (final token in registry.tokens.values.where(_isFontFamilyToken)) {
    buffer.writeln(
      '  static const String ${token.path.last} = '
      '${_dartStringLiteral(registry.resolvedValue(token).toString())};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class GeneratedCatchActivityPigmentTokens {');

  for (final token in registry.tokens.values.where(_isActivityColorToken)) {
    buffer.writeln(
      '  static const Color ${token.path[1]} = '
      '${_dartColorValue(registry.resolvedValue(token))};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln()
    ..writeln('abstract final class GeneratedCatchWebsiteTokens {');

  for (final token in registry.tokens.values.where(_isWebsiteToken)) {
    buffer.writeln(
      '  static const double ${_camel(token.path.skip(1))} = '
      '${_dartDimensionNumber(registry.resolvedValue(token))};',
    );
  }

  buffer
    ..writeln('}')
    ..writeln();

  return buffer.toString();
}

Map<String, dynamic> _catchExtension(Map<String, dynamic> document) {
  final extensions = _mapValue(document[r'$extensions'], r'$extensions');
  return _mapValue(extensions['org.catch'], 'org.catch');
}

List<_FontFace> _fontFaces(Map<String, dynamic> websiteExtension) {
  final rawFontFaces = websiteExtension['fontFaces'];
  if (rawFontFaces == null) return const <_FontFace>[];
  if (rawFontFaces is! List<dynamic>) {
    throw const FormatException('website.fontFaces must be an array.');
  }
  return rawFontFaces
      .map((value) => _FontFace.fromJson(_mapValue(value, 'fontFace')))
      .toList(growable: false);
}

void _syncFontAssets(Map<String, dynamic> websiteExtension) {
  for (final fontFace in _fontFaces(websiteExtension)) {
    final source = File(fontFace.source);
    if (!source.existsSync()) {
      throw StateError('Missing font source: ${fontFace.source}');
    }
    final target = File(fontFace.target);
    target.parent.createSync(recursive: true);
    target.writeAsBytesSync(source.readAsBytesSync());
  }
}

List<String> _fontAssetFailures(Map<String, dynamic> websiteExtension) {
  final failures = <String>[];
  for (final fontFace in _fontFaces(websiteExtension)) {
    final source = File(fontFace.source);
    final target = File(fontFace.target);
    if (!source.existsSync()) {
      failures.add('missing ${fontFace.source}');
      continue;
    }
    if (!target.existsSync()) {
      failures.add('missing ${fontFace.target}');
      continue;
    }
    final sourceBytes = source.readAsBytesSync();
    final targetBytes = target.readAsBytesSync();
    if (!_sameBytes(sourceBytes, targetBytes)) {
      failures.add('stale ${fontFace.target}');
    }
  }
  return failures;
}

bool _sameBytes(List<int> a, List<int> b) {
  if (a.length != b.length) return false;
  for (var i = 0; i < a.length; i += 1) {
    if (a[i] != b[i]) return false;
  }
  return true;
}

void _writeFile(File file, String contents) {
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(contents);
}

Map<String, dynamic> _mapValue(Object? value, String label) {
  if (value == null) return <String, dynamic>{};
  if (value is Map<String, dynamic>) return value;
  if (value is Map) {
    return value.map((key, value) => MapEntry(key.toString(), value));
  }
  throw FormatException('$label must be an object.');
}

String _cssVariableName(List<String> path) {
  if (path.length == 4 && path[0] == 'theme' && path[2] == 'color') {
    return '--catch-color-${_kebab(path[1])}-${_kebab(path[3])}';
  }
  if (path.length == 3 && path[0] == 'font' && path[1] == 'family') {
    return '--catch-font-${_kebab(path[2])}';
  }
  return '--catch-${path.map(_kebab).join('-')}';
}

bool _isThemeColorToken(_Token token) =>
    token.path.length == 4 &&
    token.path[0] == 'theme' &&
    token.path[2] == 'color' &&
    token.type == 'color';

bool _isThemeGradientToken(_Token token) =>
    token.path.length == 4 &&
    token.path[0] == 'theme' &&
    token.path[2] == 'gradient' &&
    token.type == 'gradient';

bool _isSpacingToken(_Token token) =>
    token.path.length == 2 && token.path[0] == 'space';

bool _isRadiusToken(_Token token) =>
    token.path.length == 2 && token.path[0] == 'radius';

bool _isFontFamilyToken(_Token token) =>
    token.path.length == 3 &&
    token.path[0] == 'font' &&
    token.path[1] == 'family';

bool _isActivityColorToken(_Token token) =>
    token.path.length == 3 &&
    token.path[0] == 'activity' &&
    token.path[2] == 'accent' &&
    token.type == 'color';

bool _isWebsiteToken(_Token token) =>
    token.path.length == 3 &&
    token.path[0] == 'website' &&
    token.type == 'dimension';

String _dartThemeTokenName(_Token token) =>
    '${token.path[1]}${_pascal(token.path[3])}';

String _dartColorValue(Object? value) {
  final color = _mapValue(value, 'color value');
  final components = color['components'];
  if (color['colorSpace'] != 'srgb') {
    throw const FormatException(
      'Only srgb color tokens can be emitted to Dart.',
    );
  }
  if (components is! List || components.length != 3) {
    throw const FormatException('srgb color components must have 3 values.');
  }

  final red = _componentToByte(components[0]);
  final green = _componentToByte(components[1]);
  final blue = _componentToByte(components[2]);
  final alpha = color['alpha'] as num? ?? 1;
  if (alpha == 1) {
    final hex = color['hex'];
    if (hex is String) return 'Color(0xFF${hex.substring(1).toUpperCase()})';
    return 'Color(0xFF${_hexByte(red)}${_hexByte(green)}${_hexByte(blue)})';
  }
  return 'Color.fromRGBO($red, $green, $blue, ${_formatDartNumber(alpha)})';
}

String _dartGradientValue(_TokenRegistry registry, _Token token) {
  final value = _mapValue(registry.resolvedValue(token), 'gradient value');
  final type = value['type'];
  if (type != 'linear') {
    throw FormatException('Unsupported gradient type: $type.');
  }

  final begin = _mapValue(value['begin'], 'gradient begin');
  final end = _mapValue(value['end'], 'gradient end');
  final colors = value['colors'];
  if (colors is! List || colors.isEmpty) {
    throw const FormatException('gradient colors must be a non-empty array.');
  }

  final colorValues = colors
      .map((color) => _dartColorValue(_gradientColorValue(registry, color)))
      .join(', ');
  return 'LinearGradient('
      'begin: ${_dartAlignment(begin)}, '
      'end: ${_dartAlignment(end)}, '
      'colors: <Color>[$colorValues],'
      ')';
}

Object? _gradientColorValue(_TokenRegistry registry, Object? value) {
  if (value is String && _isReference(value)) {
    return registry.resolvedValue(registry.tokenForReference(value));
  }
  if (value is String && value.startsWith('#')) {
    return _hexColorValue(value);
  }
  return value;
}

Map<String, Object> _hexColorValue(String hex) {
  final normalized = hex.startsWith('#') ? hex.substring(1) : hex;
  if (normalized.length != 6) {
    throw FormatException('Expected #RRGGBB color, got $hex.');
  }
  final red = int.parse(normalized.substring(0, 2), radix: 16) / 255;
  final green = int.parse(normalized.substring(2, 4), radix: 16) / 255;
  final blue = int.parse(normalized.substring(4, 6), radix: 16) / 255;
  return <String, Object>{
    'colorSpace': 'srgb',
    'components': <num>[red, green, blue],
    'hex': '#${normalized.toUpperCase()}',
  };
}

String _dartDimensionNumber(Object? value) {
  final dimension = _mapValue(value, 'dimension value');
  if (dimension['unit'] != 'px') {
    throw const FormatException('Only px dimensions can be emitted to Dart.');
  }
  final number = dimension['value'];
  if (number is! num) {
    throw const FormatException('dimension value must be numeric.');
  }
  return _formatDartNumber(number);
}

num _requiredNumber(Map<String, dynamic> value, String key) {
  final number = value[key];
  if (number is! num) {
    throw FormatException('$key must be numeric.');
  }
  return number;
}

String _dartAlignment(Map<String, dynamic> value) {
  final x = _requiredNumber(value, 'x');
  final y = _requiredNumber(value, 'y');
  if (x == -1 && y == -1) return 'Alignment.topLeft';
  if (x == 1 && y == 1) return 'Alignment.bottomRight';
  if (x == 0 && y == 0) return 'Alignment.center';
  return 'Alignment(${_formatDartNumber(x)}, ${_formatDartNumber(y)})';
}

String _hexByte(int value) =>
    value.toRadixString(16).padLeft(2, '0').toUpperCase();

String _dartStringLiteral(String value) => "'${value.replaceAll("'", r"\'")}'";

String _formatDartNumber(num value) {
  if (value == value.roundToDouble()) return '${value.toInt()}.0';
  return value.toString();
}

String _pascal(String input) {
  final parts = input.split(RegExp(r'[-_]'));
  return parts.map((part) {
    if (part.isEmpty) return part;
    return part[0].toUpperCase() + part.substring(1);
  }).join();
}

String _camel(Iterable<String> parts) {
  final list = parts.toList(growable: false);
  if (list.isEmpty) return '';
  return list.first + list.skip(1).map(_pascal).join();
}

String _kebab(String input) {
  final buffer = StringBuffer();
  for (var i = 0; i < input.length; i += 1) {
    final char = input[i];
    final isUpper = char.toUpperCase() == char && char.toLowerCase() != char;
    if (isUpper && i > 0) buffer.write('-');
    buffer.write(char.toLowerCase() == '_' ? '-' : char.toLowerCase());
  }
  return buffer.toString();
}

void _printHelp() {
  stdout.writeln('''
Usage: dart run tool/design_tokens.dart [--check]

Generates website token CSS, website font assets, and Flutter Dart constants
from $_tokenPath.

Options:
  --check   Rebuild in memory and fail if generated outputs are stale.
''');
}

final class _TokenRegistry {
  _TokenRegistry._(this.tokens);

  final Map<String, _Token> tokens;

  factory _TokenRegistry.fromDocument(Map<String, dynamic> document) {
    final tokens = <String, _Token>{};

    void walk(Object? node, List<String> path, String? inheritedType) {
      if (node is! Map) return;
      final map = _mapValue(node, path.join('.'));
      final type = map[r'$type'] as String? ?? inheritedType;

      if (map.containsKey(r'$value')) {
        if (path.isEmpty) {
          throw const FormatException('Root token is not supported.');
        }
        final token = _Token(
          path: List<String>.unmodifiable(path),
          type: type,
          value: map[r'$value'],
        );
        tokens[token.referencePath] = token;
      }

      for (final entry in map.entries) {
        if (entry.key.startsWith(r'$')) continue;
        walk(entry.value, [...path, entry.key], type);
      }
    }

    walk(document, const <String>[], null);
    return _TokenRegistry._(tokens);
  }

  String? cssValue(_Token token) {
    final value = _resolveValue(token.value);
    return _cssValueForType(token.type, value);
  }

  Object? resolvedValue(_Token token) => _resolveValue(token.value);

  String cssValueFromExtensionValue(Object? value) {
    if (value is String && _isReference(value)) {
      final token = tokenForReference(value);
      return 'var(${_cssVariableName(token.path)})';
    }
    return _rawCssValue(value);
  }

  Object? _resolveValue(Object? value) {
    if (value is String && _isReference(value)) {
      return _resolveValue(tokenForReference(value).value);
    }
    return value;
  }

  _Token tokenForReference(String reference) {
    final path = _referencePath(reference);
    final token = tokens[path];
    if (token == null) {
      throw FormatException('Unknown token reference: $reference');
    }
    return token;
  }

  String? _cssValueForType(String? type, Object? value) {
    switch (type) {
      case 'color':
        return _colorCssValue(_mapValue(value, 'color value'));
      case 'dimension':
        return _dimensionCssValue(_mapValue(value, 'dimension value'));
      case 'number':
        return _rawCssValue(value);
      case 'fontFamily':
        return '"$value"';
      default:
        if (value is String || value is num) return _rawCssValue(value);
        return null;
    }
  }
}

final class _Token {
  const _Token({required this.path, required this.type, required this.value});

  final List<String> path;
  final String? type;
  final Object? value;

  String get referencePath => path.join('.');
}

final class _FontFace {
  const _FontFace({
    required this.family,
    required this.style,
    required this.weight,
    required this.source,
    required this.target,
    required this.url,
    required this.format,
  });

  factory _FontFace.fromJson(Map<String, dynamic> json) {
    String requiredString(String key) {
      final value = json[key];
      if (value is! String || value.isEmpty) {
        throw FormatException('fontFace.$key must be a non-empty string.');
      }
      return value;
    }

    return _FontFace(
      family: requiredString('family'),
      style: requiredString('style'),
      weight: requiredString('weight'),
      source: requiredString('source'),
      target: requiredString('target'),
      url:
          json['url'] as String? ??
          '/${requiredString('target').replaceFirst('website/', '')}',
      format: requiredString('format'),
    );
  }

  final String family;
  final String style;
  final String weight;
  final String source;
  final String target;
  final String url;
  final String format;
}

String _colorCssValue(Map<String, dynamic> value) {
  final colorSpace = value['colorSpace'];
  final components = value['components'];
  final alpha = value['alpha'] as num? ?? 1;
  final hex = value['hex'];

  if (colorSpace != 'srgb') {
    throw const FormatException(
      'Only srgb color tokens can be emitted to CSS.',
    );
  }
  if (components is! List || components.length != 3) {
    throw const FormatException('srgb color components must have 3 values.');
  }
  if (alpha == 1 && hex is String) return hex.toUpperCase();

  final red = _componentToByte(components[0]);
  final green = _componentToByte(components[1]);
  final blue = _componentToByte(components[2]);
  return 'rgba($red, $green, $blue, ${_formatNumber(alpha)})';
}

int _componentToByte(Object? value) {
  if (value is! num) {
    throw const FormatException('srgb components must be numbers.');
  }
  return (value * 255).round().clamp(0, 255);
}

String _dimensionCssValue(Map<String, dynamic> value) {
  final number = value['value'];
  final unit = value['unit'];
  if (number is! num) {
    throw const FormatException('dimension value must be numeric.');
  }
  if (unit is! String || unit.isEmpty) {
    throw const FormatException('dimension unit must be a string.');
  }
  return '${_formatNumber(number)}$unit';
}

String _rawCssValue(Object? value) {
  if (value is num) return _formatNumber(value);
  if (value is String) return value;
  throw FormatException('Cannot emit CSS value for $value.');
}

String _formatNumber(num value) {
  if (value == value.roundToDouble()) return value.toInt().toString();
  return value.toString();
}

bool _isReference(String value) =>
    value.startsWith('{') && value.endsWith('}') && value.length > 2;

String _referencePath(String value) => value.substring(1, value.length - 1);
