#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "..");
const sourcePath = path.join(scriptDir, "business_rules.json");
const dartPath = path.join(repoRoot, "lib/core/business_rules.dart");
const tsPath = path.join(repoRoot, "functions/src/shared/businessRules.ts");

const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const runScheduling = source.runScheduling ?? {};
const runAttendance = source.runAttendance ?? {};

const requiredNumbers = [
  ["runScheduling.defaultDurationMinutes", runScheduling.defaultDurationMinutes],
  ["runScheduling.minDurationMinutes", runScheduling.minDurationMinutes],
  ["runScheduling.maxDurationMinutes", runScheduling.maxDurationMinutes],
  ["runScheduling.durationStepMinutes", runScheduling.durationStepMinutes],
  ["runScheduling.scheduleLockSlotMinutes", runScheduling.scheduleLockSlotMinutes],
  ["runAttendance.selfCheckInWindowBeforeMinutes", runAttendance.selfCheckInWindowBeforeMinutes],
  ["runAttendance.selfCheckInWindowAfterMinutes", runAttendance.selfCheckInWindowAfterMinutes],
  ["runAttendance.selfCheckInMaxDistanceMeters", runAttendance.selfCheckInMaxDistanceMeters],
  ["runAttendance.hostAttendanceWindowBeforeMinutes", runAttendance.hostAttendanceWindowBeforeMinutes],
  ["runAttendance.hostAttendanceWindowAfterRunHours", runAttendance.hostAttendanceWindowAfterRunHours],
];

for (const [key, value] of requiredNumbers) {
  if (!Number.isInteger(value) || value <= 0) {
    throw new Error(`${key} must be a positive integer.`);
  }
}

if (runScheduling.minDurationMinutes > runScheduling.defaultDurationMinutes) {
  throw new Error("runScheduling.minDurationMinutes cannot exceed defaultDurationMinutes.");
}
if (runScheduling.defaultDurationMinutes > runScheduling.maxDurationMinutes) {
  throw new Error("runScheduling.defaultDurationMinutes cannot exceed maxDurationMinutes.");
}
if (runScheduling.maxDurationMinutes % runScheduling.scheduleLockSlotMinutes !== 0) {
  throw new Error("runScheduling.maxDurationMinutes must divide cleanly by scheduleLockSlotMinutes.");
}
if (runScheduling.maxDurationMinutes / runScheduling.scheduleLockSlotMinutes > 450) {
  throw new Error("Schedule lock slots exceed a safe Firestore transaction write budget.");
}

const header = [
  "// AUTO-GENERATED by tool/generate_business_rules.mjs",
  "// Source: tool/business_rules.json",
  "// DO NOT EDIT DIRECTLY.",
  "",
].join("\n");

const dart = `${header}final class CatchBusinessRules {
  const CatchBusinessRules._();

  static const runDefaultDurationMinutes = ${runScheduling.defaultDurationMinutes};
  static const runMinDurationMinutes = ${runScheduling.minDurationMinutes};
  static const runMaxDurationMinutes = ${runScheduling.maxDurationMinutes};
  static const runDurationStepMinutes = ${runScheduling.durationStepMinutes};
  static const runScheduleLockSlotMinutes = ${runScheduling.scheduleLockSlotMinutes};

  static const runSelfCheckInWindowBeforeMinutes = ${runAttendance.selfCheckInWindowBeforeMinutes};
  static const runSelfCheckInWindowAfterMinutes = ${runAttendance.selfCheckInWindowAfterMinutes};
  static const runSelfCheckInMaxDistanceMeters = ${runAttendance.selfCheckInMaxDistanceMeters};
  static const runHostAttendanceWindowBeforeMinutes = ${runAttendance.hostAttendanceWindowBeforeMinutes};
  static const runHostAttendanceWindowAfterRunHours = ${runAttendance.hostAttendanceWindowAfterRunHours};
}
`;

const ts = `${header}export const RUN_DEFAULT_DURATION_MINUTES = ${runScheduling.defaultDurationMinutes};
export const RUN_MIN_DURATION_MINUTES = ${runScheduling.minDurationMinutes};
export const RUN_MAX_DURATION_MINUTES = ${runScheduling.maxDurationMinutes};
export const RUN_DURATION_STEP_MINUTES = ${runScheduling.durationStepMinutes};
export const RUN_SCHEDULE_LOCK_SLOT_MINUTES = ${runScheduling.scheduleLockSlotMinutes};

export const RUN_SELF_CHECK_IN_WINDOW_BEFORE_MINUTES = ${runAttendance.selfCheckInWindowBeforeMinutes};
export const RUN_SELF_CHECK_IN_WINDOW_AFTER_MINUTES = ${runAttendance.selfCheckInWindowAfterMinutes};
export const RUN_SELF_CHECK_IN_MAX_DISTANCE_METERS = ${runAttendance.selfCheckInMaxDistanceMeters};
export const RUN_HOST_ATTENDANCE_WINDOW_BEFORE_MINUTES = ${runAttendance.hostAttendanceWindowBeforeMinutes};
export const RUN_HOST_ATTENDANCE_WINDOW_AFTER_RUN_HOURS = ${runAttendance.hostAttendanceWindowAfterRunHours};
`;

fs.writeFileSync(dartPath, dart);
fs.writeFileSync(tsPath, ts);
