export 'data/dashboard_recommendations_repository.dart'; // public-api: read-model data seam for dashboard recommendations
export 'presentation/activity_controller.dart';
export 'presentation/activity_screen.dart';
export 'presentation/dashboard_full_view_model.dart';
export 'presentation/dashboard_screen.dart';
export 'presentation/dashboard_stride_actions.dart';
export 'presentation/notification_route_util.dart';
export 'presentation/notifications_list_state.dart';
export 'presentation/widgets/activity_section.dart';
export 'presentation/widgets/dashboard_empty.dart';
export 'presentation/widgets/dashboard_full.dart';
export 'presentation/widgets/dashboard_section_state_card.dart';
export 'presentation/widgets/dashboard_sliver_header.dart';
export 'presentation/widgets/empty_hero_card.dart';
export 'presentation/widgets/event_focus_rail.dart';
export 'presentation/widgets/recommend_card.dart';
export 'presentation/widgets/recommendations.dart';
export 'presentation/widgets/stride_card.dart';
export 'shared/quick_actions.dart';
