// AUTO-GENERATED by tool/contracts/generate_business_rules.mjs
// Source: tool/contracts/business_rules.json
// DO NOT EDIT DIRECTLY.
final class CatchBusinessRules {
  const CatchBusinessRules._();

  static const eventDefaultDurationMinutes = 60;
  static const eventMinDurationMinutes = 30;
  static const eventMaxDurationMinutes = 240;
  static const eventDurationStepMinutes = 15;
  static const eventScheduleLockSlotMinutes = 1;

  static const eventSelfCheckInWindowBeforeMinutes = 10;
  static const eventSelfCheckInWindowAfterMinutes = 30;
  static const eventSelfCheckInMaxDistanceMeters = 200;
  static const eventHostAttendanceWindowBeforeMinutes = 10;
  static const eventHostAttendanceWindowAfterEventHours = 6;
}
