// AUTO-GENERATED by tool/generate_business_rules.mjs
// Source: tool/business_rules.json
// DO NOT EDIT DIRECTLY.
final class CatchBusinessRules {
  const CatchBusinessRules._();

  static const runDefaultDurationMinutes = 60;
  static const runMinDurationMinutes = 30;
  static const runMaxDurationMinutes = 240;
  static const runDurationStepMinutes = 15;
  static const runScheduleLockSlotMinutes = 1;

  static const runSelfCheckInWindowBeforeMinutes = 10;
  static const runSelfCheckInWindowAfterMinutes = 30;
  static const runSelfCheckInMaxDistanceMeters = 200;
  static const runHostAttendanceWindowBeforeMinutes = 10;
  static const runHostAttendanceWindowAfterRunHours = 6;
}
