#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(scriptDir, "../..");
const sourcePath = path.join(scriptDir, "business_rules.json");
const dartPath = path.join(repoRoot, "lib/core/business_rules.dart");
const tsPath = path.join(repoRoot, "functions/src/shared/businessRules.ts");

const source = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const eventScheduling = source.eventScheduling ?? {};
const eventAttendance = source.eventAttendance ?? {};

const requiredNumbers = [
  ["eventScheduling.defaultDurationMinutes", eventScheduling.defaultDurationMinutes],
  ["eventScheduling.minDurationMinutes", eventScheduling.minDurationMinutes],
  ["eventScheduling.maxDurationMinutes", eventScheduling.maxDurationMinutes],
  ["eventScheduling.durationStepMinutes", eventScheduling.durationStepMinutes],
  ["eventScheduling.scheduleLockSlotMinutes", eventScheduling.scheduleLockSlotMinutes],
  ["eventAttendance.selfCheckInWindowBeforeMinutes", eventAttendance.selfCheckInWindowBeforeMinutes],
  ["eventAttendance.selfCheckInWindowAfterMinutes", eventAttendance.selfCheckInWindowAfterMinutes],
  ["eventAttendance.selfCheckInMaxDistanceMeters", eventAttendance.selfCheckInMaxDistanceMeters],
  ["eventAttendance.firstHelloMaxDistanceMeters", eventAttendance.firstHelloMaxDistanceMeters],
  ["eventAttendance.hostAttendanceWindowBeforeMinutes", eventAttendance.hostAttendanceWindowBeforeMinutes],
  ["eventAttendance.hostAttendanceWindowAfterEventHours", eventAttendance.hostAttendanceWindowAfterEventHours],
];

for (const [key, value] of requiredNumbers) {
  if (!Number.isInteger(value) || value <= 0) {
    throw new Error(`${key} must be a positive integer.`);
  }
}

if (eventScheduling.minDurationMinutes > eventScheduling.defaultDurationMinutes) {
  throw new Error("eventScheduling.minDurationMinutes cannot exceed defaultDurationMinutes.");
}
if (eventScheduling.defaultDurationMinutes > eventScheduling.maxDurationMinutes) {
  throw new Error("eventScheduling.defaultDurationMinutes cannot exceed maxDurationMinutes.");
}
if (eventScheduling.maxDurationMinutes % eventScheduling.scheduleLockSlotMinutes !== 0) {
  throw new Error("eventScheduling.maxDurationMinutes must divide cleanly by scheduleLockSlotMinutes.");
}
if (eventScheduling.maxDurationMinutes / eventScheduling.scheduleLockSlotMinutes > 450) {
  throw new Error("Schedule lock slots exceed a safe Firestore transaction write budget.");
}

const header = [
  "// AUTO-GENERATED by tool/contracts/generate_business_rules.mjs",
  "// Source: tool/contracts/business_rules.json",
  "// DO NOT EDIT DIRECTLY.",
  "",
].join("\n");

const dart = `${header}final class CatchBusinessRules {
  const CatchBusinessRules._();

  static const eventDefaultDurationMinutes = ${eventScheduling.defaultDurationMinutes};
  static const eventMinDurationMinutes = ${eventScheduling.minDurationMinutes};
  static const eventMaxDurationMinutes = ${eventScheduling.maxDurationMinutes};
  static const eventDurationStepMinutes = ${eventScheduling.durationStepMinutes};
  static const eventScheduleLockSlotMinutes = ${eventScheduling.scheduleLockSlotMinutes};

  static const eventSelfCheckInWindowBeforeMinutes = ${eventAttendance.selfCheckInWindowBeforeMinutes};
  static const eventSelfCheckInWindowAfterMinutes = ${eventAttendance.selfCheckInWindowAfterMinutes};
  static const eventSelfCheckInMaxDistanceMeters = ${eventAttendance.selfCheckInMaxDistanceMeters};
  static const eventFirstHelloMaxDistanceMeters = ${eventAttendance.firstHelloMaxDistanceMeters};
  static const eventHostAttendanceWindowBeforeMinutes = ${eventAttendance.hostAttendanceWindowBeforeMinutes};
  static const eventHostAttendanceWindowAfterEventHours = ${eventAttendance.hostAttendanceWindowAfterEventHours};
}
`;

const ts = `${header}export const EVENT_DEFAULT_DURATION_MINUTES = ${eventScheduling.defaultDurationMinutes};
export const EVENT_MIN_DURATION_MINUTES = ${eventScheduling.minDurationMinutes};
export const EVENT_MAX_DURATION_MINUTES = ${eventScheduling.maxDurationMinutes};
export const EVENT_DURATION_STEP_MINUTES = ${eventScheduling.durationStepMinutes};
export const EVENT_SCHEDULE_LOCK_SLOT_MINUTES = ${eventScheduling.scheduleLockSlotMinutes};

export const EVENT_SELF_CHECK_IN_WINDOW_BEFORE_MINUTES = ${eventAttendance.selfCheckInWindowBeforeMinutes};
export const EVENT_SELF_CHECK_IN_WINDOW_AFTER_MINUTES = ${eventAttendance.selfCheckInWindowAfterMinutes};
export const EVENT_SELF_CHECK_IN_MAX_DISTANCE_METERS = ${eventAttendance.selfCheckInMaxDistanceMeters};
export const EVENT_FIRST_HELLO_MAX_DISTANCE_METERS = ${eventAttendance.firstHelloMaxDistanceMeters};
export const EVENT_HOST_ATTENDANCE_WINDOW_BEFORE_MINUTES = ${eventAttendance.hostAttendanceWindowBeforeMinutes};
export const EVENT_HOST_ATTENDANCE_WINDOW_AFTER_EVENT_HOURS = ${eventAttendance.hostAttendanceWindowAfterEventHours};
`;

fs.writeFileSync(dartPath, dart);
fs.writeFileSync(tsPath, ts);
