part of 'host_create_event_state_test.dart';

void _registerCreateEventDraftSignatureTests() {
  test('CreateEventDraftSnapshot signature includes dirty-only fields', () {
    const base = CreateEventDraftSnapshot(
      distance: '5',
      capacity: null,
      price: null,
      description: null,
      activityKind: 'socialRun',
      customActivityLabel: null,
      interactionModel: null,
      paceName: null,
      meetingPoint: null,
      locationDetails: null,
      meetingLocationAddress: null,
      meetingLocationPlaceId: null,
      startingPointLat: null,
      startingPointLng: null,
      selectedDateMillis: null,
      selectedStartHour: null,
      selectedStartMinute: null,
      durationMinutes: 60,
      minAge: null,
      maxAge: null,
      maxMen: null,
      maxWomen: null,
      cohortCapsEnabled: false,
      admissionPreset: 'open',
      inviteCode: null,
      dynamicPricingEnabled: false,
      dynamicPricingStep: null,
      dynamicPricingMax: null,
      cancellationPolicy: 'standard',
      eventSuccessDefaults: EventSuccessDefaults(),
      eventPhotoIds: 'photo-1',
    );
    const photoChanged = CreateEventDraftSnapshot(
      distance: '5',
      capacity: null,
      price: null,
      description: null,
      activityKind: 'socialRun',
      customActivityLabel: null,
      interactionModel: null,
      paceName: null,
      meetingPoint: null,
      locationDetails: null,
      meetingLocationAddress: null,
      meetingLocationPlaceId: null,
      startingPointLat: null,
      startingPointLng: null,
      selectedDateMillis: null,
      selectedStartHour: null,
      selectedStartMinute: null,
      durationMinutes: 60,
      minAge: null,
      maxAge: null,
      maxMen: null,
      maxWomen: null,
      cohortCapsEnabled: false,
      admissionPreset: 'open',
      inviteCode: null,
      dynamicPricingEnabled: false,
      dynamicPricingStep: null,
      dynamicPricingMax: null,
      cancellationPolicy: 'standard',
      eventSuccessDefaults: EventSuccessDefaults(),
      eventPhotoIds: 'photo-1,photo-2',
    );
    const capsChanged = CreateEventDraftSnapshot(
      distance: '5',
      capacity: null,
      price: null,
      description: null,
      activityKind: 'socialRun',
      customActivityLabel: null,
      interactionModel: null,
      paceName: null,
      meetingPoint: null,
      locationDetails: null,
      meetingLocationAddress: null,
      meetingLocationPlaceId: null,
      startingPointLat: null,
      startingPointLng: null,
      selectedDateMillis: null,
      selectedStartHour: null,
      selectedStartMinute: null,
      durationMinutes: 60,
      minAge: null,
      maxAge: null,
      maxMen: null,
      maxWomen: null,
      cohortCapsEnabled: true,
      admissionPreset: 'open',
      inviteCode: null,
      dynamicPricingEnabled: false,
      dynamicPricingStep: null,
      dynamicPricingMax: null,
      cancellationPolicy: 'standard',
      eventSuccessDefaults: EventSuccessDefaults(),
      eventPhotoIds: 'photo-1',
    );

    expect(photoChanged.signature, isNot(base.signature));
    expect(capsChanged.signature, isNot(base.signature));
    expect(
      photoChanged.toDraft(
        id: 'draft-1',
        clubId: 'club-1',
        savedAt: DateTime(2026, 7),
      ),
      base.toDraft(id: 'draft-1', clubId: 'club-1', savedAt: DateTime(2026, 7)),
    );
  });
}
