import type {
  AdminGetEventSupplyReadinessResponse,
  EventIntakeBridge,
  MarketingEventCandidate,
  MarketingOpsBridge,
} from "../types/adminTypes";

const generatedAt = "2026-07-14T08:30:00.000Z";

const sourceProfile = {
  id: "sample-official-source",
  label: "Sample official source",
  type: "official_website",
  status: "enabled",
  cadence: "weekly",
  riskLevel: "low" as const,
  allowedUse: "Synthetic preview data only.",
};

const queryTemplate = {
  id: "sample-city-events",
  template: "events in {city}",
  query: "events in Mumbai",
  cityLabel: "Mumbai",
  intent: "preview",
  priority: 1,
  status: "enabled",
};

const runPlan = {
  id: "sample-mumbai-weekly-guide",
  cityId: "mumbai",
  weekStart: "2026-07-14",
  status: "planned",
  generatedAt,
  schedule: {
    cadence: "weekly",
    publishDay: "Monday",
    lookaheadDays: 7,
  },
  budgets: {
    maxQueries: 4,
    maxSourceResults: 10,
    maxCandidatePool: 10,
  },
  automationPolicy: {
    searchProvider: "sample",
    networkFetchesEnabled: false,
    instagramScrapingEnabled: false,
    requiresHumanApprovalBeforePublish: true,
  },
  queryIds: [queryTemplate.id],
  sourceProfileIds: [sourceProfile.id],
};

const sourceResult = {
  id: "sample-source-result",
  sourceProfileId: sourceProfile.id,
  sourceLabel: sourceProfile.label,
  queryTemplateId: queryTemplate.id,
  resultType: "official_event_page",
  title: "Sample Mumbai social",
  url: "https://events.catch.local/sample-mumbai-social",
  snippet: "Synthetic source-backed preview.",
  observedAt: generatedAt,
  status: "needs_review" as const,
  riskFlags: [],
  operatorNotes: "Preview only.",
};

const eventCandidate: MarketingEventCandidate = {
  id: "sample-mumbai-social",
  normalizedEventKey: "mumbai|sample-social|bandra|2026-07-18",
  title: "Sample Mumbai social",
  category: "social",
  neighborhood: "Bandra",
  venue: "Sample venue",
  startDate: "2026-07-18",
  endDate: "2026-07-18",
  time: "7:00 PM",
  price: "Free",
  sourceResultIds: [sourceResult.id],
  sourceUrl: sourceResult.url,
  sourceLabel: sourceProfile.label,
  reviewState: "needs_review",
  requiresVerification: true,
  explicitSinglesEvent: true,
  whySinglesFriendly: "Hosted introductions create a low-pressure social.",
  publicDescription: "Synthetic event used only for Admin previews.",
  scores: {sourceTrust: 5, conversationPotential: 5},
  sourceCoverage: {
    sourceResultIds: [sourceResult.id],
    matchedSourceResults: 1,
    hasSourceUrl: true,
    hasManualInstagramReference: false,
  },
  sourceStatus: "source_backed",
  publishability: "reviewable_needs_verification",
  score: 10,
  warnings: [],
};

const summary = {
  status: "sample",
  sourceProfiles: 1,
  queryTemplates: 1,
  sourceResults: 1,
  sourceResultsNeedingReview: 1,
  eventCandidates: 1,
  reviewableCandidates: 1,
  sourceMissingCandidates: 0,
  approvedCandidates: 0,
  candidatesNeedingReview: 1,
  duplicateGroups: 0,
  recommendationSets: 1,
  contentDrafts: 1,
  exportReadyDrafts: 0,
  deliverable: "Synthetic Admin preview.",
};

export const sampleEventIntakeBridge: EventIntakeBridge = {
  schemaVersion: 1,
  program: "catch-event-intake",
  bridgeSource: "sample",
  generatedAt,
  city: {id: "mumbai", label: "Mumbai", timezone: "Asia/Kolkata"},
  weekStart: "2026-07-14",
  summary,
  sourceProfiles: [sourceProfile],
  queryTemplates: [queryTemplate],
  runPlan,
  sourceResults: [sourceResult],
  eventCandidates: [eventCandidate],
  dedupeGroups: [],
  auditTrail: [],
  commands: {},
};

export const sampleMarketingOpsBridge: MarketingOpsBridge = {
  schemaVersion: 1,
  program: "catch-marketing-ops",
  generatedAt,
  city: {id: "mumbai", label: "Mumbai", timezone: "Asia/Kolkata"},
  weekStart: "2026-07-14",
  weekEnd: "2026-07-21",
  timezone: "Asia/Kolkata",
  summary,
  guardrails: [
    "Synthetic preview only.",
    "No post, event, booking, or payment is created.",
  ],
  sourceProfiles: [sourceProfile],
  queryTemplates: [queryTemplate],
  runPlan,
  sourceResults: [sourceResult],
  eventCandidates: [eventCandidate],
  dedupeGroups: [],
  recommendationSets: [{
    id: "sample-recommendations",
    cityId: "mumbai",
    weekStart: "2026-07-14",
    weekEnd: "2026-07-21",
    tone: "singles-friendly",
    title: "Sample Mumbai plans",
    status: "draft",
    reviewState: "needs_review",
    explanation: "Synthetic preview.",
    items: [{
      id: "sample-recommendation-item",
      eventCandidateId: eventCandidate.id,
      rank: 1,
      title: eventCandidate.title,
      category: eventCandidate.category,
      neighborhood: eventCandidate.neighborhood,
      score: eventCandidate.score,
      inclusionReason: eventCandidate.whySinglesFriendly,
      warnings: [],
      reviewState: "needs_review",
      sourceStatus: "source_backed",
      publishability: "reviewable_needs_verification",
    }],
  }],
  contentDrafts: [{
    id: "sample-marketing-draft",
    recommendationSetId: "sample-recommendations",
    cityId: "mumbai",
    weekStart: "2026-07-14",
    format: "instagram_carousel",
    tone: "singles-friendly",
    status: "draft",
    reviewState: "new",
    aspectRatio: "4:5",
    delivery: {
      posting: "manual_instagram_upload",
      currentExport: "preview",
      finalImageExport: "not_available",
      autoPosting: false,
    },
    brandContract: {
      logo: "Catch _",
      headlineFont: "Archivo",
      labelFont: "IBM Plex Mono",
      bodyFont: "San Francisco",
      primitives: ["CatchBadge", "CatchButton"],
      rendererStatus: "sample",
    },
    slides: [{
      id: "cover",
      role: "cover",
      headline: "Sample Mumbai plans",
      body: "Synthetic preview for the Admin console.",
      image: null,
    }],
    caption: "Synthetic preview.",
    ctas: [],
  }],
  auditTrail: [],
  commands: {},
};

export const sampleEventSupplyReadiness:
AdminGetEventSupplyReadinessResponse = {
  generatedAt,
  source: "sample",
  importPlan: {
    summary: {
      candidates: 0,
      proposedCreates: 0,
      writeReady: 0,
      blocked: 0,
      waitingReview: 0,
      rejected: 0,
      duplicateEventKeys: 0,
      actionsByStatus: {},
      actionsByPlatform: {},
    },
    policy: {
      status: "disabled",
      writeEnabled: false,
      reason: "Synthetic preview data never enables event imports.",
    },
    generatedFrom: {
      externalEventCandidateQueue: "sample",
      batches: [],
      reviewDecisionBatches: [],
      locationResolutionBatches: [],
    },
    guardrails: ["No canonical event writes."],
    actions: [],
    commands: {},
  },
  executionPlan: {
    summary: {
      importActions: 0,
      createActions: 0,
      skipped: 0,
      blocked: 0,
      schemaInvalid: 0,
      wouldCreate: 0,
      payloadValid: 0,
      payloadInvalid: 0,
      actionsByStatus: {},
    },
    policy: {
      status: "disabled",
      writeEnabled: false,
      authorityModel: "sample",
      reason: "Synthetic preview data never enables event imports.",
    },
    generatedFrom: {
      externalEventImportPlan: "sample",
      importPlanGeneratedFrom: {},
    },
    guardrails: ["No canonical event writes."],
    actions: [],
    commands: {},
  },
};
