import * as admin from "firebase-admin";
import type {CallableRequest} from "firebase-functions/v2/https";
import {FakeFirestore, type FakeData} from "./programFirestore";

export function request(data: Record<string, unknown>, uid: string) {
  return {
    auth: {uid, token: {}},
    data,
    rawRequest: {},
  } as CallableRequest<unknown>;
}

export const now = admin.firestore.Timestamp.fromMillis(1_800_000_000_000);

export const transportSettings = {
  bandWindowMillis: 30 * 60 * 1000,
  maxReadyWaitMillis: 10 * 60 * 1000,
  domesticExitLagMillis: 25 * 60 * 1000,
  internationalExitLagMillis: 60 * 60 * 1000,
  vehicleClasses: [
    {id: "sedan", label: "Sedan", passengerCapacity: 3,
      luggageCapacity: 3, capabilities: [], sortOrder: 0},
    {id: "suv", label: "Innova / SUV", passengerCapacity: 6,
      luggageCapacity: 8, capabilities: ["extraLuggage"], sortOrder: 1},
  ],
};

export function baseSeed(): Record<string, FakeData> {
  return {
    "organizers/org-1": {
      hostUserId: "manager-1",
      ownerUserId: "manager-1",
      hostUserIds: ["manager-1"],
      hostProfiles: [],
    },
    "organizerPrograms/program-1": {
      organizerId: "org-1",
      kind: "wedding",
      title: "Sharma–Rao Wedding",
      timezone: "Asia/Kolkata",
      startsAt: admin.firestore.Timestamp.fromMillis(1_800_000_000_000),
      endsAt: admin.firestore.Timestamp.fromMillis(1_800_300_000_000),
      status: "active",
      capabilities: ["arrivalsTransport"],
      transportSettings,
      createdBy: "manager-1",
      createdAt: now,
      updatedAt: now,
      revision: 3,
    },
    "programPickupPoints/pp-t3": {
      programId: "program-1",
      organizerId: "org-1",
      kind: "airport",
      label: "DEL T3 arrivals",
      iataCode: "DEL",
      terminal: "T3",
      meetingZone: null,
      latitude: null,
      longitude: null,
      instructions: null,
      active: true,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programPickupPoints/pp-t1": {
      programId: "program-1",
      organizerId: "org-1",
      kind: "airport",
      label: "DEL T1 arrivals",
      iataCode: "DEL",
      terminal: "T1",
      meetingZone: null,
      latitude: null,
      longitude: null,
      instructions: null,
      active: true,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programHotels/hotel-1": {
      programId: "program-1",
      organizerId: "org-1",
      name: "Taj Palace",
      address: "Chanakyapuri",
      latitude: null,
      longitude: null,
      receptionContact: null,
      notes: null,
      active: true,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programHotels/hotel-2": {
      programId: "program-1",
      organizerId: "org-1",
      name: "ITC Maurya",
      address: "Diplomatic Enclave",
      latitude: null,
      longitude: null,
      receptionContact: null,
      notes: null,
      active: true,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programGuests/guest-1": {
      programId: "program-1",
      organizerId: "org-1",
      displayName: "Rohan Sharma",
      householdId: null,
      contactId: null,
      phoneE164: "+919999900001",
      email: null,
      externalReference: null,
      invitationStatus: "notInvited",
      rsvpStatus: "accepted",
      source: "manual",
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programGuests/guest-2": {
      programId: "program-1",
      organizerId: "org-1",
      displayName: "Vikram Rao",
      householdId: null,
      contactId: null,
      phoneE164: "+919999900002",
      email: null,
      externalReference: null,
      invitationStatus: "notInvited",
      rsvpStatus: "accepted",
      source: "manual",
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programTravelLegs/leg-1": {
      programId: "program-1",
      organizerId: "org-1",
      guestId: "guest-1",
      partyId: null,
      kind: "inbound",
      flightNumber: "AI847",
      carrierCode: "AI",
      originIata: "BOM",
      destinationIata: "DEL",
      scheduledArrivalAt:
        admin.firestore.Timestamp.fromMillis(1_800_000_000_000),
      estimatedArrivalAt: null,
      actualArrivalAt: null,
      flightStatus: "scheduled",
      flightInstanceId: null,
      international: false,
      pickupPointId: "pp-t3",
      destinationHotelId: "hotel-1",
      destinationLabel: null,
      readiness: "expected",
      readyAt: null,
      claimedByUid: null,
      claimedAt: null,
      manualCurbAt: null,
      manualCurbNote: null,
      passengers: 2,
      luggageUnits: 3,
      requiredCapabilities: [],
      dedicatedVehicle: false,
      source: "planner",
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programTravelLegs/leg-2": {
      programId: "program-1",
      organizerId: "org-1",
      guestId: "guest-2",
      partyId: null,
      kind: "inbound",
      flightNumber: "6E2041",
      carrierCode: "6E",
      originIata: "BLR",
      destinationIata: "DEL",
      scheduledArrivalAt:
        admin.firestore.Timestamp.fromMillis(1_800_000_600_000),
      estimatedArrivalAt: null,
      actualArrivalAt: null,
      flightStatus: "scheduled",
      flightInstanceId: null,
      international: false,
      pickupPointId: "pp-t1",
      destinationHotelId: "hotel-1",
      destinationLabel: null,
      readiness: "expected",
      readyAt: null,
      claimedByUid: null,
      claimedAt: null,
      manualCurbAt: null,
      manualCurbNote: null,
      passengers: 1,
      luggageUnits: 1,
      requiredCapabilities: [],
      dedicatedVehicle: false,
      source: "planner",
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
    "programStaffGrants/program-1__greeter-1": {
      organizerId: "org-1",
      programId: "program-1",
      uid: "greeter-1",
      displayName: "Arjun",
      phoneLastFour: "0001",
      duties: [{
        duty: "airportGreeter", expiresAtMillis: 1_800_086_400_000,
        pickupPointIds: ["pp-t3"],
        hotelIds: [],
      }],
      status: "active",
      createdBy: "manager-1",
      createdAt: now,
      expiresAt:
        admin.firestore.Timestamp.fromMillis(1_800_000_000_000 + 86_400_000),
      revokedBy: null,
      revokedAt: null,
      updatedAt: now,
      revision: 1,
    },
    "programStaffGrants/program-1__greeter-2": {
      organizerId: "org-1",
      programId: "program-1",
      uid: "greeter-2",
      displayName: "Sana",
      phoneLastFour: "0002",
      duties: [{
        duty: "airportGreeter", expiresAtMillis: 1_800_086_400_000,
        pickupPointIds: ["pp-t3"],
        hotelIds: [],
      }],
      status: "active",
      createdBy: "manager-1",
      createdAt: now,
      expiresAt:
        admin.firestore.Timestamp.fromMillis(1_800_000_000_000 + 86_400_000),
      revokedBy: null,
      revokedAt: null,
      updatedAt: now,
      revision: 1,
    },
    "programStaffGrants/program-1__dispatcher-1": {
      organizerId: "org-1",
      programId: "program-1",
      uid: "dispatcher-1",
      displayName: "Meera",
      phoneLastFour: "0003",
      duties: [{
        duty: "transportDispatcher", expiresAtMillis: 1_800_086_400_000,
        pickupPointIds: [],
        hotelIds: [],
      }],
      status: "active",
      createdBy: "manager-1",
      createdAt: now,
      expiresAt:
        admin.firestore.Timestamp.fromMillis(1_800_000_000_000 + 86_400_000),
      revokedBy: null,
      revokedAt: null,
      updatedAt: now,
      revision: 1,
    },
    "programStaffGrants/program-1__hotelier-1": {
      organizerId: "org-1",
      programId: "program-1",
      uid: "hotelier-1",
      displayName: "Dev",
      phoneLastFour: "0004",
      duties: [{
        duty: "hotelDesk", expiresAtMillis: 1_800_086_400_000,
        pickupPointIds: [],
        hotelIds: ["hotel-1"],
      }],
      status: "active",
      createdBy: "manager-1",
      createdAt: now,
      expiresAt:
        admin.firestore.Timestamp.fromMillis(1_800_000_000_000 + 86_400_000),
      revokedBy: null,
      revokedAt: null,
      updatedAt: now,
      revision: 1,
    },
    "transportVendors/vendor-1": {
      organizerId: "org-1",
      name: "Sharma Cabs",
      contactName: null,
      phoneE164: null,
      programIds: ["program-1"],
      active: true,
      notes: null,
      createdAt: now,
      updatedAt: now,
      revision: 1,
    },
  };
}

export function deps(firestore: FakeFirestore,
  overrides: Record<string, unknown> = {}) {
  return {
    firestore: () => firestore as unknown as FirebaseFirestore.Firestore,
    checkRateLimit: async () => undefined,
    now: () => now,
    getUserByPhoneNumber: async (phoneNumber: string) =>
      ({uid: "new-staff-1", displayName: "New Staff",
        phoneNumber} as admin.auth.UserRecord),
    ...overrides,
  } as never;
}


/** A physical curb observation, distinct from the default expected roster. */
export function readySeed(): Record<string, FakeData> {
  const seed = baseSeed();
  seed["programTravelLegs/leg-1"] = {
    ...seed["programTravelLegs/leg-1"], readiness: "ready", readyAt: now,
  };
  return seed;
}
