Map<String, Object?> crmEmptyAudiencePageData() => {
  'organizerId': 'organizer-1',
  'contacts': const <Object?>[],
  'nextCursor': null,
  'matchCount': 0,
  'matchCountCoverage': 'exact',
  'sourceCoverage': 'exact',
  'projectionVersion': 1,
};

Map<String, Object?> crmSavedAudienceData() => {
  'organizerId': 'organizer-1',
  'audienceId': 'audience-1',
  'scope': 'organizerCrm',
  'name': 'Regulars',
  'status': 'active',
  'definition': {
    'join': 'all',
    'predicates': [
      {'kind': 'computedSegment', 'segmentId': 'regular'},
    ],
  },
  'definitionHash':
      'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
  'definitionVersion': 1,
  'revision': 1,
  'lastPreviewMatchCount': 12,
  'lastPreviewAtMillis': 1700000000000,
  'createdAtMillis': 1700000000000,
  'updatedAtMillis': 1700000000000,
};

Map<String, Object?> crmManualSendTaskData({
  String status = 'queued',
  bool active = true,
  int revision = 1,
  int openCount = 0,
  int? openedAtMillis,
  String deliveryMode = 'byHand',
}) => {
  'organizerId': 'organizer-1',
  'taskId': 'task-1',
  'contactId': 'contact-1',
  'displayName': 'Asha Rao',
  'routeId': 'personalWhatsappHandoff',
  'deliveryMode': deliveryMode,
  'status': status,
  'active': active,
  'revision': revision,
  'phoneE164': '+919876543210',
  'prefillText': 'Would you like to join us?',
  'openCount': openCount,
  'createdAtMillis': 1700000000000,
  'updatedAtMillis': 1700000000000,
  'openedAtMillis': openedAtMillis,
  'expiresAtMillis': 1702592000000,
};

Map<String, Object?> crmContactDetailData() => <String, Object?>{
  'organizerId': 'organizer-1',
  'contactId': 'contact-1',
  'displayName': 'Asha',
  'sourceDisplayName': 'Asha Rao',
  'displayNameOverride': 'Asha',
  'phoneE164': '+919876543210',
  'email': null,
  'linkedAccount': true,
  'identityState': 'verified',
  'identityConfidence': 'verified',
  'contactDetailsEditable': false,
  'ambiguousCandidateContactIds': <String>[],
  'whatsappAdminSuppressed': true,
  'whatsappPermission': {
    'status': 'optedIn',
    'evidenceStatus': 'complete',
    'receiptId': 'permission-1',
    'source': 'hostFormResponse',
    'sourceFormId': 'form-1',
    'sourceFormTitle': 'Social run sign-up',
    'decisionAtMillis': 1699000000000,
    'identityStrength': 'phoneVerified',
  },
  'origins': [
    {
      'originId': 'origin-1',
      'sourceKind': 'hostForm',
      'sourceEntityKind': 'hostFormResponse',
      'formId': 'form-1',
      'formTitle': 'Social run sign-up',
      'eventId': 'event-1',
      'eventTitle': 'Social run',
      'observedAtMillis': 1699000000000,
    },
  ],
  'originsTruncated': false,
  'traits': {
    'expectedEventCount': 4,
    'attendedEventCount': 3,
    'cancelledEventCount': 0,
    'noShowCount': 1,
    'importedEventCount': 1,
    'attendanceRate': 0.75,
    'segmentIds': ['repeat_attendee'],
    'whatsappStatus': 'optedIn',
    'smsStatus': 'unknown',
    'sourceCoverage': 'exact',
  },
  'revenue': {
    'coverage': 'exact',
    'amounts': [
      {
        'currency': 'INR',
        'amountMinor': 450000,
        'factCount': 3,
        'sources': [
          {'source': 'catchPayment', 'amountMinor': 450000, 'factCount': 3},
        ],
      },
    ],
  },
  'events': [
    {
      'eventId': 'event-1',
      'displayName': 'Social run',
      'eventOriginMode': 'externalCompanion',
      'eventProvider': 'eventbrite',
      'source': 'hostImport',
      'status': 'checkedIn',
      'checkedIn': true,
      'eventStartAtMillis': 1700000000000,
      'revenues': [
        {
          'currency': 'INR',
          'amountMinor': 150000,
          'source': 'hostImport',
          'factCount': 1,
          'allocation': 'perAttendee',
        },
      ],
    },
  ],
  'eventsTruncated': false,
  'timeline': [
    {
      'kind': 'form',
      'timelineId': 'timeline-form-1',
      'responseId': 'response-1',
      'formId': 'form-1',
      'formTitle': 'Social run sign-up',
      'action': 'submitted',
      'answeredQuestionCount': 3,
      'occurredAtMillis': 1699000000000,
    },
  ],
  'timelineTruncated': false,
  'timelineCoverage': {
    'forms': 'exact',
    'events': 'exact',
    'sends': 'exact',
    'replies': 'partial',
    'replyObservation': 'catchAndManagedWhatsappOnly',
  },
  'activeMerges': [
    {
      'mergeReceiptId': 'receipt-1',
      'sourceContactId': 'contact-2',
      'sourceDisplayName': 'Asha R.',
      'evidence': ['sameVerifiedPhone', 'managerConfirmed'],
      'conflicts': <String>[],
      'movedFactCount': 4,
      'mergedAtMillis': 1700000001000,
    },
  ],
  'revision': 7,
};
